### ISSUE TITLE
Support "SBI\x1d" file format

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#107]
On this page there is a collection of SBI files which don't seem to load.
http://linuxsynths.com/JuceOPLPatchesDemos/juceopl.html

They are a custom collection made for the plugin JuceOPLVSTI.
Possibly it's just a question of handling the header to support it, I haven't tried yet.

**Comment by jpcima** [comment]
Relevant source code here.

https://github.com/bsutherland/JuceOPLVSTi/blob/761069397cd38db308013146cbe731c9922d82d9/Source/PluginProcessor.cpp#L547-L564

For me the loading has worked as the regular "DOS SBI" case.
But the instruments categorized into the "percussions" category of the importer.

**Comment by Wohlstand** [comment]
I'll check this at home, for now I'm riding on the bus and at me is rainy :rain:

**Comment by jpcima** [comment]
Here I just deposit a WOPL of said patchset, for the guy who asked me to have this set, and also if you're interested to give it a try.

[JuceOPLPatches.wopl.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2545406/JuceOPLPatches.wopl.gz)

**Comment by Wohlstand** [comment]
It works
https://github.com/Wohlstand/OPL3BankEditor/pull/108
