### ISSUE TITLE
wopl: impossible to load a bank which is not at least a 1:1

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#109]
The library `wopl_file` will allow to save a WOPL without the percussion bank, however the editor will not accept to load this file.

I think there exist 2 ways to solve this:

1. accept loading a file which contains 0 of either melodic or percussion banks
2. make `wopl_file` fail on banks which don't have >=1 melodic and percussion

**Comment by Wohlstand** [comment]
Looks like Editor should auto-create the missing bank as blank

**Comment by jpcima** [comment]
Ok then. It must be changed in both editor and wopl_file that in can allow such banks.
I take it that the first bank listed must not be required necessarily to be the 0:0.

**Comment by Wohlstand** [comment]
Okay, as this was fixed some time ago, I'll close this.
https://github.com/Wohlstand/OPL3BankEditor/pull/110
