### ISSUE TITLE
wopl: get the latest file version

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#112]
I think it will be nice if the WOPL file library would expose the version number of the latest stable standard.
It is indicated in the source file as `wopl_latest_version` but not accessible.

At the moment the file specification evolves, this permits me to drop the new library in my source code, and the new format will be automatically saved without changing my code.

**Comment by Wohlstand** [comment]
Good idea! :+1:

**Comment by jpcima** [comment]
It's not as much a problem as I imagined, as I have realized that `version` = 0 is the same meaning as latest. This is a precision to add in the header documentation.

**Comment by Wohlstand** [comment]
@jpcima , did you done something with it and I can close this?

**Comment by Wohlstand** [comment]
Closed as abandoned.
