### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by grauw** [Wohlstand/OPL3BankEditor#121]
Hi,

I’m trying to build on MacOS.

Building with qmake works but I get no sound.

Since the build instructions say cmake automatically detects audio libraries, I’m trying that:

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.12.0/ -DQWT_INCLUDE_DIR=/usr/local/Cellar/qwt/6.1.3_4/lib/ ..
```

However I’m getting the following error, and make fails to build:

```
[grauw] ~/Development/OPL3BankEditor/build § cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.12.0/ ..
!! Optional feature summary:
!!   RtMidi: ON
!!   RtAudio: ON
!!   Qwt: /usr/local/lib/qwt.framework
!!   Plots: ON
-- Configuring done
CMake Error: Attempt to add a custom rule to output "/Users/grauw/Development/OPL3BankEditor/build/CMakeFiles/measurer_autogen.rule" which already has a custom rule.
CMake Error in CMakeLists.txt:
  Cannot find source file:

    /Users/grauw/Development/OPL3BankEditor/build/CMakeFiles/measurer_autogen

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

-- Generating done
-- Build files have been written to: /Users/grauw/Development/OPL3BankEditor/build
```

Any suggestions?

**Comment by jpcima** [comment]
Hello.

> Building with qmake works but I get no sound.

It was intended to result in sound, although I've never had a chance myself to run macOS to check it.
The qmake project was written to enable CoreAudio and MIDI in the macOS case, cf. `src/audio/ao_rtaudio.pri` `src/midi/midi_rtmidi.pri`
 (btw I believe to have just seen `CoreMIDI` misspelled as `CoreMidi`, need to make a quick fix)

>However I’m getting the following error, and make fails to build:

All I can say, it's related to the source generation in relation with `CMAKE_AUTOMOC`.
Supposedly, it's a script internal to cmake which enables this generation. It may be worth trying a later version of cmake.
I'll try this as soon as I set up a virtualization for Mac testing.

**Comment by grauw** [comment]
Cool, let me know if there’s something I can do.

**Comment by jpcima** [comment]
I forgot to ask the obvious first: have you loaded one of provided banks, such as `Bank_Examples/fat4.op3`?

Because yeah, it's happened to have reporting of "no sound" issues when there just wasn't instruments loaded in the software.
(I think, we really should load a default bank)

**Comment by grauw** [comment]
Ok, doh, that made the qmake build work fine. Because it listed instrument names on the left I figured it had loaded a default bank.

Feel free to close this issue unless you want to further investigate the cmake issue of course :).
