### ISSUE TITLE
DOSBox raw importer issues

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#126]
There remain some elements to fix in the DRO file importer.

- [ ] Support of rhythm-mode instruments

- [x] Feedback/Algorithm register

SBTimbre has a reset command on the Fb/Alg register `C0`.
Despite this, the note sounds as if these have not been reset by the command.
It's validated by DOSBox and also by replaying the dro file in `adplay`.

It seems not a misinterpretation of DRO format; I logged register writes from `libadplug` linked to `adplay`, and it also showed the sequence.

```
[CH00] C0: 3D   // set Con=1 Fb=6
[CH00] C0: 30   // set Con=0 Fb=0 (?)
[CH00] B0: 31   // key-on
[CH00] B0: 11   // key-off
```

[sbtimbre-sample.tar.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2741604/sbtimbre-sample.tar.gz)

- [x] fine with DOSBox Windows dumps but not Linux

Quoted from @gnidorah:

>@jpcima Thank you! Here is the issue I've got.
Lets take a single-instrument track from ultima6 as most simple case. I've tried to grab it on windows and linux dosbox multiple times (using dosbox 0.74-2 everywhere), and by some reason OPL3BankEditor always read linux capture incorrectly, while windows capture is read ok (4 instruments which don't match original versus 1 matching instrument). If I however convert linux capture into imf by dro2imf utility, OPL3BankEditor reads instrument from that imf correctly.
Here are the files for demonstration:
[1.zip](https://github.com/jpcima/ADLplug/files/2746628/1.zip)

- [ ] Music tags

Apparently libadplug shows there is a header extension of DOSBox files which permits tagging.
It may be needed to handle this case.

**Comment by jpcima** [comment]
I posted a fix and I just merged it, to make quick testing possible.
It's needed to ignore the upper register bank on OPL2, which wasn't done before.
I think the instruments are way better now.

**Comment by gnidorah** [comment]
@jpcima Yay, that helped, thank you!
Another issue is that some instruments have no sound. Here is the zip dro+imf to compare. Setup tune from Flight of The Amazon Queen.
ins 3, channel 6
ins 4, channel 7
ins 1, channel 8
As you see some ADSR values are not filled.
[2.zip](https://github.com/Wohlstand/OPL3BankEditor/files/2750412/2.zip)

**Comment by jpcima** [comment]
i guess it's needed to increase the total level of the carriers.
I saw an implementation of this in IMF import (and in OPN2).
In IMF, only 2-op algorithms are supported. In this case, I should add support of all 6 possible algorithms, because dro can also encode 4-op instruments.

**Comment by jpcima** [comment]
About the music tag format, I link the information about it.
It's not required to implement it, because the format has it at the end of file, and the OPL register payload has a size field in the header.

https://github.com/adplug/adplug/blob/master/src/dro2.cpp#L91-L126
https://github.com/adplug/adplug/blob/master/src/dro.cpp#L99-L135

**Comment by gnidorah** [comment]
@jpcima That works good, thank you much! Will try more things with it later.

**Comment by jpcima** [comment]
>That works good, thank you much! Will try more things with it later.

@gnidorah Did it work? let us know, so we can close the issue.

**Comment by gnidorah** [comment]
@jpcima Still works fine! Thank you much for the hard work!

**Comment by Wohlstand** [comment]
Question: does this understands rhythm-mode percussions? I guess, there are rhythm-mode percussions may exist, and there are has different way of use, I even can explain how, but, after when I'll come to my home, but in short words: in 0xBD register is the rhythm-mode bit and 5 bits are key on/off per each slot:
- bass drum (does use of two operators)
- snare (does use of one carrier operator)
- tom (does use of one modulator operator, channel is shared with snare)
- cymbal (does use of one carrier operator)
- hihat (does use of one modulator operator, channel is shared with cymbal)

**Comment by gnidorah** [comment]
@Wohlstand In [2.zip](https://github.com/Wohlstand/OPL3BankEditor/files/2750412/2.zip)/queen_000.dro "Ins 0, channel 1" is percussion (and all notes sound the same).

**Comment by jpcima** [comment]
Captures of SBTimbre instruments using rhythm-mode channels.
They use register BD, and they are not currently recognized by the importer.

[BassDrm1.dro.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2922121/BassDrm1.dro.gz)
[Cymbal1.dro.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2922122/Cymbal1.dro.gz)
[HiHat1.dro.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2922123/HiHat1.dro.gz)
[Snare1.dro.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2922124/Snare1.dro.gz)
[TomTom6.dro.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2922125/TomTom6.dro.gz)

**Comment by Wohlstand** [comment]
The off topic note: make rhythm mode drums for CMF importer, it's easy but I'll need to scan music tracks to identify which drums are rhythm mode

**Comment by jpcima** [comment]
What's a good reference documentation on rhythm channel operation?
I still try to figure out how this stuff works precisely.

**Comment by Wohlstand** [comment]
Closed because of no response for a long time.
