### ISSUE TITLE
NO AUDIO!

### ISSUE THREAD

**Issue by NiBBa256** [Wohlstand/OPL3BankEditor#132]
On startup it lists instruments but they don't play, when I opened manually a bank it was fixed, anyhow that is misleading, it would be very nice if you could make it more obvious that no bank file is opened.

**Comment by jpcima** [comment]
The blank instruments have been designated by gray entries in the dev version.
The feature is not part of the software release, yet.
This would certainly be nice for sure, as it has been a source of confusion for new users multiple times.

**Comment by sneakernets** [comment]
I've considered making a crude demonstration bank, like an `example.wopl` to load to show all features.

Such a thing would be displayed on first load but I'm afraid that would make things even more confusing.

**Comment by sneakernets** [comment]
Yeah That'll work. I'll make a quick little wopl this week with the following goodies:
* A few basic 2-op instruments
* A few basic 4-op instrument
* A few basic "DMX Style" instruments
* A few percussion presets using the percussion mode
* A few examples of crazy sounds in a special bank (to show you can make any instrument in any location as long as you specify the location in your MIDI)

**Comment by papiezak** [comment]
I assembled something like this in like 30 minutes:

[example.zip](https://github.com/Wohlstand/OPL3BankEditor/files/2992956/example.zip)
I can make a OPNA/OPN2 version, running through all algorithms if you need it

**Comment by Wohlstand** [comment]
Closing this as abandoned.

**Comment by Wohlstand** [comment]
If something still needed, please re-open and give a note.
