### ISSUE TITLE
Some Instruments saved in DMX OP2 format play incorrectly in DMX

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#14]
I'm attaching a ZIP file with an audio file, with the following:

* A Clarinet in DMXOPL with OPL3BankEditor
* The same clarinet played in DMX
* A Trumpet in DMXOPL with  OPL3BankEditor
* The same trumpet played in DMX

As you can hear, the sound is much harsher than it should be. I'm not sure why.

I'm also attaching the WOPL and op2.

[BUGREPORT.zip](https://github.com/Wohlstand/OPL3BankEditor/files/1427639/BUGREPORT.zip)

**Comment by sneakernets** [comment]
Seems like it's the 2nd voice that is the problem on these! the first voice is fine, as far as I can tell!

**Comment by Wohlstand** [comment]
Does that happens on DosBox in real DooM (which one of games? 1'th, 2'nd?), on OPL Synth like ZDoom's, or DooM 1/2 on real hardware?

**Comment by sneakernets** [comment]
It happens in DOS Doom on both Doom and Doom 2 v1.9 versions that I have. Chocolate Doom as well. It also affects NukeyTYT's DMX player, since that is also Chocolate Doom code. ZDoom seems to do its own thing on these? I assume that's due to Randi's custom code in ZDoom. It's hard to explain but it still sounds off in ZDoom, just not as bad as DMX. :thinking:

GZDoom is a lost cause at this point, so I didn't test it. but there is *something* going on here.

**Comment by Wohlstand** [comment]
Also, I just now remembered an another bug, but on side of Apogee Sound System: In the AM voices the "modulator" is always muted. I.e. all AM voices on Apogee Sound System are broken because of this bug. It's hearable in Blood on level in hospital where music theme has vibraphone which is in bank must be different but muted modulator makes sine only.

**Comment by Wohlstand** [comment]
Closes as idling.
