### ISSUE TITLE
Feature: highlight differences between two banks

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPL3BankEditor#141]
As requested by @sneakernets. (sneakernets/DMXOPL#48) Ability to

- load two banks
- compare instrument entries betwwen two banks, seek and find/highlight diffs

would be very helpful.

**Comment by Wohlstand** [comment]
I think, @jpcima is making some sort of...

**Comment by jpcima** [comment]
Right now there exists this utility which enables git-diff between files:
https://github.com/jpcima/wopl-textconv

**Comment by Wohlstand** [comment]
I have merged that just now, and I did few fixes around you'll see :fox_face: :wink

**Comment by sneakernets** [comment]
I will check this out! thank you!!!

**Comment by papiezak** [comment]
I did a quick take a look and it looks fairly OK, the only weird thing is that when comparing o 2-op instrument against a completely different dual one, it only shows "it uses a different algorithm", forgoing any other differences.
But I guess it doesn't need to be that verbose 😉

**Comment by jpcima** [comment]
>it only shows "it uses a different algorithm", forgoing any other differences.

It's on purpose, for compactness, as it would probably not offer a very useful output.
It would be a triviality to modify this behavior.

**Comment by papiezak** [comment]
no feeedback from @sneakernets = no bugs.
Closing then.
