### ISSUE TITLE
Startup crash on incorrect chip setting

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#142]
When `chip-emulator` has a bad setting value, generator's chip is not instantiated and the software will crash with access into a null pointer.

**Comment by Wohlstand** [comment]
Looks like the protector is needed... Damn!

**Comment by Wohlstand** [comment]
Just now I did a smal fix, please check it out...

**Comment by Wohlstand** [comment]
If it works, I'll apply the same fix for OPN2-BE which, looks like, has same bug

**Comment by jpcima** [comment]
It worked, it was a crash before the fix, and then no longer, and Nuked OPL appeared as checked.
(for the record the bug occurred to me after that I added the "custom" pseudo-chip, and went back to the ordinary branch)

**Comment by Wohlstand** [comment]
Yeah, becasuse it was tried to initialize non-existing emulator and crashing because of weird logic, so, it's fine now :fox_face: :+1:
