### ISSUE TITLE
Sound may play through wrong device in Windows

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#144]
In Windows, I have a Bluetooth headset that I use for music and other things, but OPL3BankEditor always wants to play from my main sound card, and *not* my Bluetooth headset. It's not that big of a deal as I can attach my headset to my soundcard with a cable, but I would like to tinker with sounds at work and Bluetooth is the only way to go there. 👀

**Comment by Wohlstand** [comment]
OPL3-BE does use of default audio output device, however, a good idea to give a choice by which audio output device do streaming the audio: by default, or by another one. @jpcima have used RtAudio library to replace Qt Multimedia which is ineffective for low-latency audio output.

**Comment by jpcima** [comment]
It's needed to keep the device name in the config as a string, and re-enable this one rach time if found.
Also, check the device's channel count for 2 or more, or RtAudio will throw and crash the program.

**Comment by jpcima** [comment]
@Wohlstand yeah, so is this one considered fixed with the merge of audio device selection #146 ?

**Comment by Wohlstand** [comment]
Yeah, so, it's the outdated and needs to be closed, however, didn't confirm by @sneakernets to be completely free to close this, but, will close as it's now ancient issue :fox_face:
