### ISSUE TITLE
Cannot load inpout32.dll for hardware opl playback

### ISSUE THREAD

**Issue by SilverMiner** [Wohlstand/OPL3BankEditor#147]
Если прога для новых компов без агп портов и драйверов для SB16 например, почему она просит реальный чип? Почему нельзя запустить прогу только из-за этого?

**Comment by Wohlstand** [comment]
Это дело опционально и не должно требоваться, по умолачиню должен работать один из эмуляторов чипа, если случайно не включить прокси на чип.
Кажется что-то [ну очень похоже на это](https://github.com/Wohlstand/OPL3BankEditor/issues/118#issuecomment-464790722), и вроде это починили, а на какой сборке это? Нужно попробовать на сборочке по свежее.

Эта фича предназначена не обязательно для SB16, а, например, для карточек, у которых есть аппаратный клон OPL3-чипа, например, C-Media, которые работают на PCI и может работать на вполне современной машине (сам испытывал на компьютере с процом AMD-A8, мать на одних PCI-Express, и UEFI-загрузка, там виндо-семёрка, и через C-Media-карточку я смог запустить чип, главное знать адрес и смещение, указать его в настройках, и тогда должно заработать).

**Comment by SilverMiner** [comment]
У меня теперь на запуске
there are no creative audio products installed and running on the system
that support asio


пн, 25 мар. 2019 г. в 20:30, Vitaly Novichkov <notifications@github.com>:

**Comment by jpcima** [comment]
I'm not sure to understand the question here. (I'm not a russian speaker)
This message is usually seen on Windows Vista and greater.
After you run the software once "as administrator", InpOut support willl be installed, and following runs do not ask for administrator mode to work.

The driver of InpOut will attempt to set up itself on first run, when not present.
I think, maybe packaging the software as an installer will allow to resolve this issue in a better way.

**Comment by Wohlstand** [comment]
Закрываю за ненадобностью. Жан-Пьер Сималёнду ответил всё.
