### ISSUE TITLE
Importing/Saving .opli instuments doesn't work

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPL3BankEditor#16]
This one is weird. While importing .oplis from "bank_examples" folder works, I can't truly save my own opli's because when I try to import them, bank editor whines:  "Can't open bank file because bad file format"
I don't even know when it broke...
Here's my example:
[opli.zip](https://github.com/Wohlstand/OPL3BankEditor/files/1523762/opli.zip)

**Comment by Wohlstand** [comment]
I think, it's a bug! I have upgraded format version and I think, I accidentally broke OPLI support... Will emergencily fix this!

**Comment by papiezak** [comment]
OK, now it's alright. Thanks!

**Comment by sneakernets** [comment]
Oh thank goodness! I thought my files corrupted!
