### ISSUE TITLE
UI looks glitchy after 1.5.1 release

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#161]
![editor151](https://user-images.githubusercontent.com/32672779/83508851-d0b39300-a4ca-11ea-95a5-567ea675ec3f.JPG)

Note the weird gap before "Level" and "Frequency multiplication" spinboxes. OPN2 Bank Editor doesn't have that problem.

**Comment by Wohlstand** [comment]
It's not a glitch, it's, as I guess, just a tweak against text alignment of these labels :thinking: 
I'll try to tweak some...
![Peek 2020-06-02 13-21](https://user-images.githubusercontent.com/6751442/83509428-16288e00-a4d4-11ea-8bd7-590b4e9d32ee.gif)

**Comment by Wohlstand** [comment]
![изображение](https://user-images.githubusercontent.com/6751442/83510651-0ad66200-a4d6-11ea-998b-5a9ce5cfb4df.png)

**Comment by freq-mod** [comment]
Tak

**Comment by Wohlstand** [comment]
wtedy zrobię tak:
![Снимок экрана_2020-06-02_13-39-33](https://user-images.githubusercontent.com/6751442/83510937-820bf600-a4d6-11ea-9370-1052273f5016.png)

**Comment by Wohlstand** [comment]
![Снимок экрана от 2020-06-02 13-46-32](https://user-images.githubusercontent.com/6751442/83511557-7cfb7680-a4d7-11ea-9603-070da4b914fa.png)
Tada!

**Comment by freq-mod** [comment]
Wygląda już nieźle, dzięki!
