### ISSUE TITLE
Some percussion-mode tones aren't being played

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#166]
I made an experimental bank with use of OPL percussion mode. Instruments of "hi-hat" type aren't being played. At all - adlmidiplay throws error about missing percussion instrument. Yet they're present - in OPL3-BE you can preview them.
Maybe it has something to do with being assigned to operator 1 rather than operator 2 (carrier) and synth doesn't know what to do about it
[YMF278.wopl.zip](https://github.com/Wohlstand/libADLMIDI/files/5360198/YMF278.wopl.zip) - bank file in question

**Comment by Wohlstand** [comment]
I made a fix just now, please run a full delays recomputation to make the fix work.
P.S. Please don't change the "note offset" value together with a drum note, here is a small confusion at OPL3-BE itself that didn't resolve yet: note-offset doesn't work together with a drum note-number, but works at libADLMIDI.

**Comment by freq-mod** [comment]
Looks like that one is fixed, but I can hear another glitch with hi-hat note number affecting snare drum (?)

Let's take wikipedia's MIDI sample -  [YMF278.wopl.zip](https://github.com/Wohlstand/OPL3BankEditor/files/5360761/YMF278.wopl.zip) (contains also a bank with fixed delays and note offsets) after kick/snare solo sections that sounds properly, there is closed/open hihat solo. And after that, snare drum will become much higher in pitch, almost like a beep.

**Comment by Wohlstand** [comment]
Instruments except for bass drum (hi-hats and cymbals), using tom-tom's frequency channel to set own
http://www.shikadi.net/moddingwiki/OPL_chip#Percussion_Mode

**Comment by Wohlstand** [comment]
At the same time, rhythm mode system itself needs an improvement

**Comment by freq-mod** [comment]
I see. But by "frequency" it's meant note number or just Frequency Multiplication parameter?
Either way, yeah, percussion mode sounds weird and main issue was fixed already. Thanks!

**Comment by Wohlstand** [comment]
> I see. But by "frequency" it's meant note number or just Frequency Multiplication parameter?

Frequency is a tone frequency, resulted after the computation of note number, pitch bend factors, etc. FM chips do use the tone frequency in hertz value to define the note/tone.
