### ISSUE TITLE
Not work for 64-bit windows

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/OPL3BankEditor#167]
There're no x64 version of this can be worked, even installed C++ Runtime!!

I'm using Windows 10, 64-Bit of the OS.

**Comment by Wohlstand** [comment]
Odd, but easy to fix, thanks for a note!
For OPL3-BE the C++ runtime is unneeded because I use MinGW which gives own runtime DLLs I ship with the project.

**Comment by Wohlstand** [comment]
Added just now, gonna to see how it will be built...

**Comment by Wohlstand** [comment]
The build runs here https://ci.appveyor.com/project/Wohlstand/opl3bankeditor

**Comment by LoveBodhi** [comment]
The other one is OPN Bank Editor

**Comment by Wohlstand** [comment]
If this build will work, to OPN-BE it's just copy the code piece to apply the same building :wink:

**Comment by Wohlstand** [comment]
Okay, here is a first build: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/opl3-bank-editor/opl3-bank-editor-dev-win64.zip
Please test it, does it work for you?

**Comment by LoveBodhi** [comment]
Yes!

**Comment by Wohlstand** [comment]
Great! So, closing this. :fox_face:  Thank for a report! :fox_face:
