### ISSUE TITLE
[Enhancement]More keyboard shortcuts

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#168]
Why not? Especially `Delete` key, could be used to delete single instruments on the list.
"Add Bank" function could be assigned to `Ctrl+A` binding, `Ctrl+S` for sounding delay calculation and so on...

**Comment by Wohlstand** [comment]
Good idea :fox_face: 

P.S. `Ctrl+S` is busy with the "save" action.

**Comment by Wohlstand** [comment]
That quick to add, simply assign those hotkeys to menu items

**Comment by freq-mod** [comment]
>P.S. Ctrl+S is busy with the "save" action.

You're right, i forgot, damn But anyway, it can be `Shift+Ctrl+S`, these keys aren't that far from each other :man_shrugging:

**Comment by Wohlstand** [comment]
About "delete instrument" that I better assign to "clear instrument", because real "delete instrument" is allowed for AdLib-like banks which don't containing the 127/127 sets: just the biggest hive of instruments.

**Comment by Wohlstand** [comment]
Shift+Delete I would assign into clear bank :thinking:

**Comment by Wohlstand** [comment]
Ctrl+Shift+S won't set, I'll set Ctrl+Alt+S

**Comment by Wohlstand** [comment]
(I mean, for the single instrument)

**Comment by Wohlstand** [comment]
Added

**Comment by Wohlstand** [comment]
If that fine, I'll make same into OPN2-BE

**Comment by freq-mod** [comment]
That's fine, thanks a lot. But I would also appreciate a shortcut for "delete current instrument" and "import instruments" if possible.

**Comment by Wohlstand** [comment]
Ctrl+I for import. The "Delete current instrument" why? it's a need for adlib-like banks only, the "clear" should be fine, or for what you need that?

**Comment by Wohlstand** [comment]
"Clear instrument" makes the sort of a "safe deletion" without removing the entry physcially. Otherwise, physical deletion of entry makes an offset of all next instruments back to one id.

**Comment by freq-mod** [comment]
>Otherwise, physical deletion of entry makes an offset of all next instruments back to one id.

Yeah, now I thought about this I won't really use it much.
Maybe instead a shortcut for global sounding delay : Ctrl+ Alt +G?

**Comment by Wohlstand** [comment]
Don'

**Comment by Wohlstand** [comment]
So, I closing this and porting the result to OPN2-BE

**Comment by Wohlstand** [comment]
Added same into OPN2-BE
