### ISSUE TITLE
[Linux] Bank Editor crashes on startup 

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#169]
Reinstalled Os on my machine, while editor itself built fine, it won't run:

`Init audioOut...`
`Using RtAudio API 2`
`Desired latency 0.02`
`Buffer size 960`
`terminate called after throwing an instance of 'RtAudioError'`
`  what():  RtApiPulse::probeDeviceOpen: error connecting output to PulseAudio server.`
`Przerwane (zrzut pamięci)
`
Pulseaudio was installed, are there any other depedences for that?

**Comment by Wohlstand** [comment]
Are other sound programs works fine? :thinking:

**Comment by freq-mod** [comment]
Yes, mpv and firefox (alsa?) work fine

**Comment by Wohlstand** [comment]
What distro you have? Did you rebuilt Editor after OS reinstall? (try to full clean-up of config and re-generating it from scratsh, did you that already?)

**Comment by Wohlstand** [comment]
Otherwise, let's ask @jpcima who know guts of the RtAudio library better

**Comment by freq-mod** [comment]
>What distro you have? Did you rebuilt Editor after OS reinstall? (try to full clean-up of config and re-generating it from scratsh, did you that already?)

- Arch Linux x64
- I wiped my entire drive, so let's say yes, I already did

**Comment by freq-mod** [comment]
OK I have no idea what has happened, rebooted my PC and suddenly it started working, weird...

**Comment by freq-mod** [comment]
Still I think, in the wiki, "building from sources" section, more dependencies must be mentioned...

**Comment by Wohlstand** [comment]
Can you point some names? I'll add them...

**Comment by freq-mod** [comment]
For pacman based distros:
qt5-serialport (optional, for serial port support)
qt5-tools
qt5-base
and now it seems, pulseaudio

...and, probably much more unless `base-devel` was installed. For Debian derivatives, I will check...

**Comment by Wohlstand** [comment]
I am at work, and I can't make myself, you can commit the update yourself, I'll accept your PR. :fox_face:

**Comment by jpcima** [comment]
Hi, I've also met some reliability problems with the Pulseaudio driver, not in OPL3-BE specifically, but all software which use of RtAudio on my side.
It was for this reason that I switched some software to libsoundio, but not checked if upstream has corrected problems since.
