### ISSUE TITLE
Another issue (?) regarding .opli importing

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPL3BankEditor#17]
OK - so I tried to import a few instruments that I made a while back (they were most likely v2, but I can be wrong) and it returns with "can't open bank file because bad file format"). I highly doubt they're corrupted in any way, so it can be a bug. @sneakernets noticed it.
[FX.zip](https://github.com/Wohlstand/OPL3BankEditor/files/1538266/FX.zip)

**Comment by Wohlstand** [comment]
Bank? You must use "open single instrument" button for individual instrument files. Dropping of single instrument files is works for bank files as I wasn't made an ability to accept individual instruments too

**Comment by papiezak** [comment]
But I used open single instrument option I don't know why it says bank, that also seems weird to me.

**Comment by papiezak** [comment]
OK, now it's works okay now after  c943489

**Comment by Wohlstand** [comment]
I wanted to notify you, but I was busy at my job. However you have an Eagle Eye! :) I glad you have quickly caught and tested the fix. I'll close this.
