### ISSUE TITLE
[Windows] liboplproxy64.dll throws error during launch 

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#171]
`Oops... I have failed to load_chipInit@0 function:` | `Oops... I have failed to load_chipPoke@8 function:`
`Error 127`
`Continuing without FM sound`

Bank editor throws these error boxes anytime I start it under Windows 10 x64. Running it with user admin mode doesn't help.
Tool itself works fine, though.

**Comment by Wohlstand** [comment]
I guess, the dll didn't packed into archive...

**Comment by Wohlstand** [comment]
The mess of a build script

**Comment by Wohlstand** [comment]
Okay, I see the true reason - wrong calls. I did some work to fix that, so, going to push...

**Comment by Wohlstand** [comment]
One thing I should to do - do initialize OPL Proxy library on the first attempt to use it, rather initialize it since startup.

**Comment by Wohlstand** [comment]
Done! So, the actual initialization of hardware OPL3 module will happen once you'll choose it.

**Comment by freq-mod** [comment]
Right, now it starts correctly, thanks!
