### ISSUE TITLE
[Feature Request] Save preferred MIDI standard to registry/config file after closing

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#172]
Currently, default MIDI standard is XG. You can change it, but after you close the program it gets resetted back to XG. It can be bothersome to have to set it to, for example, GS every time, so it can be saveable setting after closing.

Iirc, on Linux, there is a .config file, while on Windows all defaults are stored in registry

**Comment by Wohlstand** [comment]
I think it's a mistake that the saving of the state for this option has lacked..

**Comment by Wohlstand** [comment]
Made!

**Comment by freq-mod** [comment]
Thanks! Please also make this change into OPN-BE as well
