### ISSUE TITLE
How to adjust the algorithm

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPL3BankEditor#175]
Can OPL3 adjust the algorithm in the editor? I am used to using OPN instruments, and I don't know much about OPL3.

**Comment by freq-mod** [comment]
In case of OPL3, there aren't algorithms per se. In 4-op mode, there are four possible permutations (so, algorithms):
1. Check the 4-op instrument checkbox
2. Set the synthesis types. FM and FM = algorithm 0 in OPN chips, AM and FM = algo 2, FM and AM = algo 4 (or 6, i don't know for sure) and AM + AM is alg 7.

**Comment by Wohlstand** [comment]
Closing as answered.
