### ISSUE TITLE
import OPN instruments

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPL3BankEditor#176]
OPL3 has 4op mode (2 + 2op), which looks very similar to OPN. Even if it is different, I think many parameters are common.
Even though OPN supports the definition of algorithm, OPL3 can also implement the algorithm in other ways.
Parameters such as ssg-eg that don't exist in OPL3 can be discarded directly.

**Comment by denjhang** [comment]
In fact, there is a conversion program to convert OPN VGM to OPL VGM. Please refer to this project 
https://github.com/digital-sound-antiques/vgm-conv
I tried a lot of VGM files of OPN, which can be converted to OPL normally. A few musical instruments will have strange sounds, but it is not impossible.

**Comment by Wohlstand** [comment]
The problem that OPN2 instruments has different features that OPL3 doesn't have, and opposite. Some possible heuristic is posislble, but, it will require manual editing of the instrument after it being converted.

**Comment by Wohlstand** [comment]
Closing as abandoned. If still needed, please re-open.
