### ISSUE TITLE
Possible typo in a readLE() array index

### ISSUE THREAD

**Issue by redtide** [Wohlstand/OPL3BankEditor#177]
Shouldn't be 3 the array index value in [this line](https://github.com/Wohlstand/OPL3BankEditor/blob/9bb47da0c080cffbed69644461e82a980cbbdece/src/common.cpp#L42)?

**Comment by Wohlstand** [comment]
Oh, really, damn... thank you for the catch!

**Comment by Wohlstand** [comment]
Fixed!

**Comment by jpcima** [comment]
You have commited this in the OPN2BankEditor wrong branch.

**Comment by Wohlstand** [comment]
I work at that branch now, I'll merge it into master once I'll finish. It's a kick on my ass to finish this as fast as possible.
