### ISSUE TITLE
No sound under Windows 10 (and ASIO?)

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#178]
One of BT Discord server users reported problems with not being able to hear anything when using this tool.

their audio device list in audio configuration menu: 
![unknown](https://user-images.githubusercontent.com/32672779/112974920-5045d900-9153-11eb-9cd9-dba94ec01d2d.png)
reportedly none of these three options above work

**Comment by freq-mod** [comment]
>Dumb question, but do they have an instrument set up? The default new instrument settings produce no sound.

supposedly yes, they tried to load a bank. I also don't have problem with realtek ASIO :man_shrugging:

**Comment by devinacker** [comment]
I'm having the same issue on Windows 8.1.

Specifically, the only options available for me are:
* Default device (no audio, I'm guessing the "default" is just ASIO4ALL?)
* ASIO4ALL, which complains about not being able to open the regular system audio device
* Realtek ASIO, which immediately crashes the editor somehow

Is there simply no option to use a non-ASIO audio device anymore?

**Comment by Wohlstand** [comment]
The last thing I had to update is the RT-Audio library and seems like it's the problem of this library I guess... 
The library itself is here: https://github.com/thestk/rtaudio

**Comment by Wohlstand** [comment]
I got the same mess at my OPN2BE too on Linux Mint. Okay, I had to downgrade the RtAudio library, and the result now works!
Please try again. :fox_face: :+1:

**Comment by Wohlstand** [comment]
I guess, the RtAudio library got messed up, so, I downgraded it into the state from 2018.

**Comment by freq-mod** [comment]
Allegedly, it still doesn't work...

**Comment by freq-mod** [comment]
Is it possible to add support for DirectSound/WASAPI?

**Comment by Wohlstand** [comment]
The RtAudio library has already DirectSound and WASAPI on aboard, I may guess, the library gets first who got initialized first? 🤔

**Comment by Wohlstand** [comment]
@jpcima, do you think is a good idea to add an option to add the switching between audio APIs when available? I mean:
- on Windows
  - ASIO (where it works)
  - WASAPI
  - DirectSound
  - WinMM
- on Linux and xBSD
  - PulseAudio
  - ALSA
- on macOS
  - CoreAudio (I guess, on macOS is not necessary as CoreAudio is a one way here)

**Comment by freq-mod** [comment]
i'm not @jpcima but that's an only sane way to fix these windows problems. For example, BambooTracker and ZorroTracker have these options, and I don't recall having any audio problems with sound :man_shrugging:

**Comment by jpcima** [comment]
It's addressed in the PR #182

**Comment by freq-mod** [comment]
Changing the audio device solved the problem, thanks!
