### ISSUE TITLE
Enhancement: Voice Swap

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#18]
Referencing my issue on DMXOPL: https://github.com/sneakernets/DMXOPL/issues/17 (single-voice compatibility)

Some of my patches had the unfortunate fate of being "Swapped", that is, the main "voice" in the double voice set being on the bottom instead of the top. So on Vanilla Doom, when the voice limit is hit and the 2nd voice is omitted, the 1st voice may sound awful.
Example is this Vibraphone patch:
![image](https://user-images.githubusercontent.com/5595293/34843977-a52861ac-f6d5-11e7-82ee-2b55c37efbd2.png)

This patch used to be "swapped", with the bottom voice being the top voice - which sounds awful by itself. I had to manually swap these, which took a bit of time. If only I could do that with a command!

**Comment by Wohlstand** [comment]
I think this has sense for pseudo-4-op mode only as real 4-op mode will cause VERY different sounding result. Also I want to let mute any of two voices in two-voice mode to polish each voice individually.

**Comment by sneakernets** [comment]
That would be a great addition!

**Comment by Wohlstand** [comment]
Just now I have made this: https://github.com/Wohlstand/OPL3BankEditor/commit/3a3b79bff0b688109c1e989475d26b6d5f11100a
* Swap voices you will find in the **Edit** menu and it will be shown only when two-voice mode is turned on
* Ability to paste one of voices instead of entire instrument

**Comment by sneakernets** [comment]
Will check this out in the morning!

**Comment by sneakernets** [comment]
Works just fine! thank you!
