### ISSUE TITLE
Error: Cannot load inpout32.dll for hardware OPL playback.

### ISSUE THREAD

**Issue by adambiser** [Wohlstand/OPL3BankEditor#180]
I get this on program start up.  Windows 10.

**Comment by Wohlstand** [comment]
- Try to run the 64-bit version
- First run needs to be done with admin rights as I know :thinking: 

The quite from https://www.highrez.co.uk/downloads/inpout32/:
> the first time it is run, it must be elevated on Vista and later (run as Administrator).

**Comment by Wohlstand** [comment]
Anyway, the question: did you tried to use the real OPL3 chip on your sound card? (like C-Media has one) Or that error got appeared unexpectedly and you wanted to just use the emulator? I guess that older versions may pop up this error. The newer version got this thing being fixed, and it will run the initialization of the library once you'll select the "real OPL3 chip" emulator entry in the menu.

**Comment by adambiser** [comment]
I'm using release 1.5.1, win32.
That error appears unexpected at startup.  I have no real OPL3 chip and haven't made any attempt to use it.

**Comment by Wohlstand** [comment]
>  That error appears unexpected at startup. I have no real OPL3 chip and haven't made any attempt to use it.

So, please download the dev version from the ReadMe and try it again, it shouldn't appear again

**Comment by adambiser** [comment]
The dev version (1.5.2) does not show that error on startup.  Thanks.
