### ISSUE TITLE
PulseAudio device does not support output.

### ISSUE THREAD

**Issue by johnsonb2** [Wohlstand/OPL3BankEditor#181]
After building on Arch Linux from https://aur.archlinux.org/packages/opl3bankeditor-git:

`Init audioOut...
Using RtAudio API 2
Desired latency 0.02
Buffer size 882
terminate called after throwing an instance of 'RtAudioError'
  what():  PulseAudio device does not support output.
fish: Job 1, 'opl3_bank_editor' terminated by signal SIGABRT (Abort)`

It's strange because the OPN2 Bank Editor (also built from the AUR) loads up just fine.

**Comment by Wohlstand** [comment]
The first in the thing that something was happening because of the RtAudio library... :thinking:

**Comment by Wohlstand** [comment]
I got the same mess at my OPN2BE too on Linux Mint. Okay, I had to downgrade the RtAudio library, and the result now works!
Please try again. :fox_face: :+1:

**Comment by johnsonb2** [comment]
Works now, thanks.

**Comment by Wohlstand** [comment]
So, I'll leave the bug report at RtAudio itself as it's a critical issue of the library.
