### ISSUE TITLE
[Feature request] Add A2I instrument format support

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#184]

**Comment by Wohlstand** [comment]
There is an actual work that got started at the [wip-adlibtracker](https://github.com/Wohlstand/OPL3BankEditor/tree/wip-adlibtracker) branch, the main challenge right now is to implement all compression algorithms used by these files. The source code is available and open, but it coded in Pascal (https://github.com/ijsf/at2). The fact the thing does use of a non-standard modified way of known compression algorithms, and therefore we need to port them from Pascal into C++ to get them being used.

**Comment by Wohlstand** [comment]
But wait.... It's a duplicate of #170 !

**Comment by freq-mod** [comment]
Oh, I'm sorry, I was in hurry and I haven't noticed it
