### ISSUE TITLE
Append file extentions while exporting

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#186]
Currently, when exporting an instrument from the bank, file doesn't get the extension appended to it. "snare.opli" gets exported to just "snare". Can this be changed?

**Comment by Wohlstand** [comment]
I guess that depends on the save dialog, but ye, that's abnormal, and I should make the workaround, it's quick to make it...

**Comment by freq-mod** [comment]
Thanks!

**Comment by Wohlstand** [comment]
🦊👍
