### ISSUE TITLE
OPL3BankEditor fails to start and crashes

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPL3BankEditor#188]
https://user-images.githubusercontent.com/61811583/122069403-c0e1c500-ce27-11eb-8b80-28579970ca82.mp4

This seems to conflict with the Cubase LE AI Elements 8 64bit I installed. The flashing window shows the ASIO software "Generic Low Latency ASIO Driver" that comes with Cubase.

**Comment by Wohlstand** [comment]
You need to open the audio settings and choose the different audio drivers from ASIO (use WASAPI, DirectSound, or WinMM). ASIO support is a slight mess here, on some computers it won't work at all.

**Comment by Wohlstand** [comment]
Anyway, I guess, I better disable the ASIO support at all here... it's here a source of the pain.

**Comment by denjhang** [comment]
I modified some asio settings and now this appears. . .
![截图未命名0615222808](https://user-images.githubusercontent.com/61811583/122071156-179bce80-ce29-11eb-89ef-3d8fccfda286.jpeg)

**Comment by Wohlstand** [comment]
Try to download the updated build of OPL3-BE and try how it works now

**Comment by Wohlstand** [comment]
> I modified some asio settings and now this appears. . .

Looks like some exception got thrown in the code, which is possible to check in the debugger. I don't own any ASIO-equipped sound cards and I am not able to test anything like. I had to completely disabled ASIO usage in my code, and I hope, this should work now.

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/122072805-7e6db780-ce2a-11eb-89d0-ecb90e763e41.mp4

**Comment by denjhang** [comment]
Please help me compile an OPL3-BE for win32 and let me try it.

**Comment by Wohlstand** [comment]
First off, you'll need to install the Qt toolchain:
https://wohlsoft.ru/pgewiki/Installing_Qt_on_Windows
Also, install GIT for Windows and CMake, then, clone the repo together with submodules:
```
git clone --recursive https://github.com/Wohlstand/OPL3BankEditor.git
```
Then, open or CMakeLists.txt, or "FMBankEdit.pro" (both projects supported and working)

**Comment by denjhang** [comment]
The current version of QT is 5.12.11, and the optional items in the installation seem to be somewhat different. I don't see options like cmake.
![Qt-010](https://user-images.githubusercontent.com/61811583/122089585-7c5f2500-ce39-11eb-8412-c9ecaf1d3d6d.png)

**Comment by Wohlstand** [comment]
That depends which installer you will use

**Comment by denjhang** [comment]
So I decided to use the same version as in https://wohlsoft.ru/pgewiki/Installing_Qt_on_Windows.

**Comment by Wohlstand** [comment]
Also, please check the registry for just in a case:
`HKEY_CURENT_USER/Software/Wohlstand/OPL3BankEditor` or something like, and remove all fields that mention the audio driver, or something, or simply remove the entire branch, will that help? I may guess that errors left in the settings may cause such stupid crashes

**Comment by Wohlstand** [comment]
That probably is the same issue as #163 or something... :thinking:

**Comment by denjhang** [comment]
It does not seem to be #163, this registry record does not seem to record any information.
![截图未命名0616111903](https://user-images.githubusercontent.com/61811583/122153063-d17c5480-ce94-11eb-9e15-55f8abbbfb59.jpeg)
![截图未命名0616111858](https://user-images.githubusercontent.com/61811583/122153066-d3461800-ce94-11eb-8dcb-11ae9658e4b5.jpeg)

**Comment by denjhang** [comment]
I tried to run QT to compile OPL3-BE, and a warning appeared.

Running D:\Qt\Tools\CMake_64\bin\cmake.exe -S E:/开源合集/Wohlstand-FMMIDI驱动/OPL3BankEditor-master -B C:/Users/Administrator/AppData/Local/Temp/QtCreator-WmLLDj/qtc-cmake-eYkBvbBb -GNinja "-DCMAKE_BUILD_TYPE:STRING=Debug" "-DCMAKE_PROJECT_INCLUDE_BEFORE:PATH=d:/Qt/Tools/QtCreator/share/qtcreator/package-manager/auto-setup.cmake" "-DQT_QMAKE_EXECUTABLE:STRING=D:/Qt/5.14.2/mingw73_64/bin/qmake.exe" "-DCMAKE_PREFIX_PATH:STRING=D:/Qt/5.14.2/mingw73_64" "-DCMAKE_C_COMPILER:STRING=d:/Qt/Tools/mingw730_64/bin/gcc.exe" "-DCMAKE_CXX_COMPILER:STRING=d:/Qt/Tools/mingw730_64/bin/g++.exe" in C:\Users\Administrator\AppData\Local\Temp\QtCreator-WmLLDj\qtc-cmake-eYkBvbBb.
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: d:/Qt/Tools/mingw730_64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: d:/Qt/Tools/mingw730_64/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find Qwt (missing: QWT_LIBRARY QWT_INCLUDE_DIR) 
CMake Error at D:/Qt/Tools/CMake_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/Qt/Tools/CMake_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  D:/Qt/Tools/CMake_64/share/cmake-3.19/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:39 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/AppData/Local/Temp/QtCreator-WmLLDj/qtc-cmake-eYkBvbBb/CMakeFiles/CMakeOutput.log".
CMake process exited with exit code 1.
Elapsed time: 00:02.
Running D:\Qt\Tools\CMake_64\bin\cmake.exe -S E:/开源合集/Wohlstand-FMMIDI驱动/OPL3BankEditor-master -B C:/Users/Administrator/AppData/Local/Temp/QtCreator-WmLLDj/qtc-cmake-eYkBvbBb in C:\Users\Administrator\AppData\Local\Temp\QtCreator-WmLLDj\qtc-cmake-eYkBvbBb.
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find Qwt (missing: QWT_LIBRARY QWT_INCLUDE_DIR) 
CMake Error at D:/Qt/Tools/CMake_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  D:/Qt/Tools/CMake_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  D:/Qt/Tools/CMake_64/share/cmake-3.19/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:39 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/AppData/Local/Temp/QtCreator-WmLLDj/qtc-cmake-eYkBvbBb/CMakeFiles/CMakeOutput.log".
CMake process exited with exit code 1.
Elapsed time: 00:00.

**Comment by denjhang** [comment]
I have successfully compiled OPL3-BE without any problems.

**Comment by Wohlstand** [comment]
Okay, does this thing works when the ASIO code got been disabled?

**Comment by denjhang** [comment]
When the ASIO code was deleted, there was no problem at all.

**Comment by Wohlstand** [comment]
So, thank you for confirmation that this mess has finally gone! :fox_face:
