### ISSUE TITLE
MIDI IN support for Midi Keyboards?

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#19]
Not really sure where to place this, if this belongs in ADLMidi, or if this would require something new entirely. So I'm placing it here.

The benefits of this should be obvious. Not sure if it could link into the real-time dispatcher code or not. There is a QT5 library called Drumstick that claims to add MIDI IN functionality to QT5 although I haven't looked into it much. I use a Mac Mini with MacOS in my studio with CoreAudio support and would love to improv a bit with patches on my midi keyboard as I design them instead of using the mouse or QWERTY board.

Yes, I am a musician after all! I just wanted to know your thoughts on this.

**Comment by Wohlstand** [comment]
Good idea!
Also, I need to rework current notes sequencer handler which sucks for now because key-off of one key will turn off all other keys too. Also, hitting of a keys too fast will result no sound as key gone too fast.

**Comment by Wohlstand** [comment]
One small thing: you must rework the generator's internal to map pressed notes to correctly off each of it. For now the thing is sucks: it play chords and add parallel notes, but attempt to off any of notes will off all playing notes.

**Comment by Wohlstand** [comment]
About of key mapper: for this toy tester is unnecessary use complex channel managers, as this thing is designed to test a single instrument. Therefore just keep the round robin channel management (which is made now) which will shut up oldest notes on overflow of any free channels.

**Comment by jpcima** [comment]
Yes. If you have possibility to test Mac, please do. It's not so much the code that I doubt about, but more the cmake/qmake build script.

**Comment by Wohlstand** [comment]
I'll also need to try run the build on Windows 98 to confirm it will work, otherwise I'll disable RT-Midi support on Win9x build.

**Comment by jpcima** [comment]
Let's cross fingers.. hopefully winmm will not have changed API in a time span of 20 years. :wine_glass:

**Comment by Wohlstand** [comment]
That yeah, but some jerkish functions are may be added in some age and break a whole compatibility, so, I still need to try out the thing in work, I have almost booted up my Win98 PC

**Comment by Wohlstand** [comment]
Tested that out, and thing is works on Windows 98 fine! However, I wasn't installed MIDI Yoke thing to receive MIDI events from other apps and I wasn't tested the work-flow itself...

**Comment by jpcima** [comment]
Good that the MIDI seems to work :+1: some people will surely be happy at the next release.
Next the voice management. Not sure if I still can do it now or I'll wait tomorrow.. this issue is going to be soon closed.

**Comment by Wohlstand** [comment]
About of voice management, I have some idea to implement, I'll try that now, and if that will success, then nothing need to do from your side, but I'll write my idea tomorrow, as now I gonna to sleep in a few minutes...

**Comment by jpcima** [comment]
Ca you explain more how the voice management is supposed to be done?
Need I use some knowledge of how the OPL manages its internal arrangement of 2op and 4op channels?

**Comment by Wohlstand** [comment]
Look what algorithm I wanna to make:
Here I have three channels tables for three modes: 2-op (18), pseudo-4op (9), and 4-op (6).
I gonna to have an array of "running notes", and do this management:
* Take each free new channel by round-robin like now, but check busyness state of OPL channel before to take it for use.
* When all channels are busy, kill oldest note you have.

**Comment by jpcima** [comment]
Given that just 1 instrument will play, only 1 of the 3 modes will be active at any time.
Hence, if you silence the chip when the instrument is changed, I would believe there isn't need to make a different handling depending on mode.
You will take the task to implement this, or do I?

**Comment by Wohlstand** [comment]
> Given that just 1 instrument will play, only 1 of the 3 modes will be active at any time.

Yeah, one of three modes will be used here.

> Hence, if you silence the chip when the instrument is changed, I would believe there isn't need to make a different handling depending on mode.

Any change of instrument will silence all chip channels before to replace properties, not only by mode switch.

> You will take the task to implement this, or do I?

Today I'll try something myself now, but if I'll not notify you before tomorrow, feel free to begin work by yourself :wink:

**Comment by jpcima** [comment]
Ok I can fill my time with some other little tasks. I want adljack to have a few more things.
When you make it, you run no risk of coming back to yell at me when I send you my crappy code. :smile:

**Comment by jpcima** [comment]
It's a good start, but it still definitely has some issues.
By playing the keys somewhat vigorously I am able to trigger sticky notes.
These sticky notes, when I replay them on the keyboard, don't seem to go away. It creates a new note which stacks up with the previous one.

**Comment by jpcima** [comment]
I give you first impressions after 5 little minutes of testing.
But after all wait, maybe my MIDI interface is tired and needs its reboot, because it was up for days long and I've done lots of naughty things, making lots of underruns while debugging code; so maybe it has just gone crazy and it's why. Reinitializing everything and trying again.

**Comment by jpcima** [comment]
**Update**

It's great work. I'm not having having any problems at all. :+1: 
If the latency is ignored, which is to expect, because the MIDI messages are handled in the same event loop as all Qt messages, and so is intertwined with GUI processing. (I did this in full knowledge, for it was the easiest way to avoid dealing with any concurrency problems)

**Comment by sneakernets** [comment]
I would love to test this out when it's ready to do so. is it?

**Comment by jpcima** [comment]
@sneakernets  Yes it's ready. Certainly not perfect, the MIDI support is minimal to say the least.
It's merged in the development version.

**Comment by sneakernets** [comment]
Awesome! The lack of midi support in the past is why my organ project stalled, so I can get that off the ground finally. 

Skoal! 🎉 🍷 🎊

**Comment by jpcima** [comment]
It's a cool project. I'm glad if I can somewhat help to advance it forward.  :wine_glass:

**Comment by jpcima** [comment]
There is not an upper bound on MIDI latency I can give you, currently.
The MIDI gets processed when the GUI finishes processing its events, which includes repainting the screen, and it's a delay fluctuating with how busy it is.

> how much of a lift would it be to separate processing into another thread for speed?

Possibly not difficult at all, but I have to get a deeper understanding of code to see how all things articulate together. I will do it at some point.
For now, the bank editor is subject to latencies in both audio and midi. I have myself a synthesizer for libADLMIDI which has low-latency audio for all platforms. If I port all these things, an excellent audio/MIDI support will be achieved, but I must think how to integrate in the existing software.

**Comment by jpcima** [comment]
The current audio is not a good processing model.. I'm gonna scrap this stuff and redesign.

**Comment by jpcima** [comment]
@beastlike @sneakernets latency problems are fixed in master and looking good, having no problem on my side. You're welcome to give it a test.
A bit more work needed to achieve god mode latency, but it should be quick to do.

**Comment by Wohlstand** [comment]
Anyway, it's some question about of MIDI Input devices on Windows 98: there are pretty dirty and junky, and possibly a wrong charset... I'll provide the screenshot for some moment...

**Comment by jpcima** [comment]
The port names arrive as std::string, and std::string->QString converts as utf8, not the local codepage.
You have characters out of the ascii range in your device names?

**Comment by Wohlstand** [comment]
Yeah, seems I need to detect Win9x and use fromLocal8bit source instead:
![default](https://user-images.githubusercontent.com/6751442/40274611-86b7a9bc-5be3-11e8-934a-8a1b203b9489.png)

**Comment by jpcima** [comment]
You observe winmm to behave different in other Windows?

**Comment by Wohlstand** [comment]
I mean:
```cpp
#if QT_VERSION < 0x050000
        if(QSysInfo::windowsVersion() == QSysInfo::WV_98 || QSysInfo::windowsVersion() == QSysInfo::WV_Me)
            ports[i] = QString::fromLocal8Bit(name.c_str());
        else
#endif
            ports[i] = QString::fromStdString(name);
```
However, result is still damned:
![default](https://user-images.githubusercontent.com/6751442/40274650-a641f656-5be4-11e8-9111-db819536aca3.png)

**Comment by Wohlstand** [comment]
Anyway, it's probably a crap on a side of Qt or something that deals with UTF8 incorrectly:
![default](https://user-images.githubusercontent.com/6751442/40274663-18eb4cf2-5be5-11e8-999a-1581aae7e66d.png)

**Comment by jpcima** [comment]
https://msdn.microsoft.com/en-us/library/8w60z792.aspx

> When the locale code page changes, the behavior of the locale-dependent set of functions changes to that dictated by the chosen code page. By default, all locale-dependent functions begin execution with a locale code page unique to the "C" locale. You can change the internal locale code page (as well as other locale-specific properties) by calling the `setlocale` function. A call to `setlocale(LC_ALL, "")` sets the locale to that indicated by the operating system user locale.

If Qt's `toLocal8Bit` obeys to the C locale setup, this thing may be worth trying.

**Comment by Wohlstand** [comment]
Okay, the reason of error in the fields is missing of `QString::fromUtf8()` calls when passing `char` array, I have fixed that. What about of MIDI Input prints, the result itself coming be junk:

I have made a super-simple program that prints names of MIDI devices:
```c
#include <stdio.h>
#include <windows.h>
#include <mmsystem.h>

int main()
{
	MIDIINCAPS deviceCaps;
	unsigned int i = 0;
	unsigned int nDevices = midiInGetNumDevs();
	for(i = 0; i < nDevices; i++)
	{
		const char *output;
#if defined( UNICODE ) || defined( _UNICODE )
		char output_u[2048];
		int len;
#endif
		midiInGetDevCaps(i, &deviceCaps, sizeof(MIDIINCAPS));
#if defined( UNICODE ) || defined( _UNICODE )
		len = WideCharToMultiByte(CP_UTF8, 0, deviceCaps.szPname, wcslen(deviceCaps.szPname), output_u, 2048, NULL, NULL);
		output_u[len] = '\0';
		output = output_u;
#else
		output = deviceCaps.szPname;
#endif
		printf("%4u: %s\n", i, output);
	}
	return 0;
}
```

And when building without of unicode:
```
> gcc miniport.c -static -o midiport -lwinmm -static-libgcc
```
Instrument names are printing semi-correct: ASCII printing fine, but non-ASCII printing clunky because of DOS and Windows charset differences.

BUT: when compiling with unicode support:
```
> gcc -DUNICODE -D_UNICODE miniport.c -static
-o midiport -lwinmm -static-libgcc
```
the captured result is worse random crap even ASCII characters now are printed damages...
Also I have found that MIDI menu gives a random crap when open it each time... I'll try to tweak some on MIDI Input thing now...

**Comment by Wohlstand** [comment]
So, when I have made next:
```cpp
    for(unsigned i = 0; i < count; ++i)
    {
        m_errorSignaled = false;
#if (QT_VERSION >= 0x050000) && !defined(_WIN32)
        std::string name = midiin->getPortName(i);
        if(m_errorSignaled)
            return false;
        ports[i] = QString::fromStdString(name.c_str());
#else
        MIDIOUTCAPSA deviceCaps;
        midiOutGetDevCapsA(i, &deviceCaps, sizeof(MIDIOUTCAPSA));
        ports[i] = QString::fromLocal8Bit(deviceCaps.szPname);
#endif
    }
```

The stuff is now finally fixed! :tada: :fox_face: :smile: 
![default](https://user-images.githubusercontent.com/6751442/40275208-d21a7ca0-5bf1-11e8-88b4-9c1b11b700a1.png)

**Comment by jpcima** [comment]
Oh oh! it's good job to have found this. However it's cleaner if you add a check of the value `getCurrentApi()` against the `WINDOWS_MM` value. RtMidi patch in perspective for me to make?

**Comment by jpcima** [comment]
`midiOutGetDevCapsA`

Wait a minute, aren't you supposed to look at **MIDI IN** devices.

**Comment by Wohlstand** [comment]
Oh, damn! You right, I looked for MidiIn, but I mostook and tried to print MidiOut devices... Ouch!

**Comment by Wohlstand** [comment]
Fixed that just now! :wink:

**Comment by jpcima** [comment]
I have to remind myself to incorporate this in the not yet merged OPN2 branch.

**Comment by Wohlstand** [comment]
Now everything is fine:
![default](https://user-images.githubusercontent.com/6751442/40275271-e7e3f21c-5bf3-11e8-9ade-b64c7b3429ec.png)

One only thing that on Win98 is ugly printing of QListWidget fields are non-ASCII:
![default](https://user-images.githubusercontent.com/6751442/40275277-f7572d90-5bf3-11e8-8ddd-e7f0d06a44e2.png)

**Comment by jpcima** [comment]
Having looked at RtMidi internals very quick, this happens: it tries to convert port to UTF8.
`ConvertToUTF8` does `MultiByteToWideChar(CP_ACP)` and then `WideCharToMultiByte(CP_UTF8)`.
If something funny happens it's probably in these function call sequence.

**Comment by beastlike** [comment]
Ok. Finally got a chance to test. 49 key controller hooked up to PC via USB, feels like zero latency on the keyboard. This is truly great work guys - playing these sounds with a keyboard is a real treat. Can't wait to try on a Win98 box with an OPL3 card!

Current testing setup:
keyboard: mAudio Keystation 49e
os: Win10 x64
cpu: i7 920
Audio Latency setting: 25ms
Chip Emulator: both Nuke OPL3 & DosBox 0.74 work 

Overall, it all works flawlessly.

Couple small issues (Can raise these as separate issues if wanted!)

Sustain pedal does not appear to work on the 49e - does this work for you guys?
Pitch wheel / mod wheel do not appear to do anything yet. (perhaps this is more enhancement request than bug) Mod wheel would be cool to hook up to a configurable parameter somehow.

Thank you for your hard work and dedication to this project!

**Comment by jpcima** [comment]
@beastlike the MIDI implementation is very incomplete. The handling code is so minimal that we have it currently written in 25 lines, to give an idea. For a summary: only the notes are working pretty much, + 2 controllers I added for reset.

This MIDI implementation has room for improvement in a myriad ways, and there are surely some low hanging fruits. Pitch bending must be one of them.
MIDI learn is a decent idea, and on the programming side would need to store some sort of meta information on the set of parameters.

I am favorable to keeping a list of MIDI features to implement, and to classify in difficulty and priority.
But a thing to remember: the editor is never intended to become a full synthesizer, it's only for purposes of a preview.

**Comment by Wohlstand** [comment]
@jpcima , If needed a complete MIDI synthesizer, then you can make your ADLJack work on Win9x, and for real card it's probably needed for me to write the usage of same "OPL Proxy" but over Windows while the current realOPL code intended to be built for DOS

**Comment by jpcima** [comment]
> then you can make your ADLJack work on Win9x

It probably would work except I ship Win32 with w64 flavored MinGW, and this doesn't run on 9x.
For that I should use the legacy MinGW out of the same archive that you use.
But then ADLjack on 9x has nearly no purpose, unless I create a specific build for hardware OPL. Then, the virtual port driver would not be compatible and that's a shame unfortunately.

**Comment by Wohlstand** [comment]
MinGW-w64 32bit probably able to target 9x

**Comment by beastlike** [comment]
@jpcima - Sustain pedal would make this very playable, even with the charming 6 note polyphony. I know the original intent wasn't to be a full fledged synth, but it's actually very close to being one! Adjusting the waveform while playing is reminiscent of playing a dx7.

Let me know if I can help in any way.

**Comment by jpcima** [comment]
> MinGW-w64 32bit probably able to target 9x

It's not. There is a startup failure about missing `AddVectoredExceptionHandler` in kernel32.
I tried fixing this myself in the MinGW CRT, but then it goes on with more missing stuff in MSVCRT.

> Sustain pedal would make this very playable

Gotta look into implementing these basic things, yeah.

**Comment by Wohlstand** [comment]
Anything was done and fine on this issue?

**Comment by jpcima** [comment]
I would consider the main issue as fixed.
There were requests for mod wheel and something like midi learning.

**Comment by Wohlstand** [comment]
Closed because of no response for a long time.
