### ISSUE TITLE
Can I use a real YMF724 board by OPL3BankEditor on modern Windows(x64)  ?

### ISSUE THREAD

**Issue by 110-kenichi** [Wohlstand/OPL3BankEditor#191]
Can I use a real YMF724 board by OPL3BankEditor on modern Windows(x64)  ?
If YES, could you please tell me the way to use it ?

**Comment by Wohlstand** [comment]
Yes, it should work if there is an OPL3-compatible interface available. First off, you need to figure the address of your sound card and then, learn the exact offset of OPL3-compatible chip. At the settings you need to set its address. Recent 64bit build of the thing should work, I added the 64bit variant of the interface driver.

**Comment by 110-kenichi** [comment]
Thank you so much!!!

So... the address of my sound card is 0x40000 ? ( Please see the attached picture. )
And, Do you know how to figure out the exact offset of OPL3 chip ?

![image](https://user-images.githubusercontent.com/40394569/152151813-1452d102-c9de-4d10-9f4d-c32eb5e09dd1.png)

**Comment by Wohlstand** [comment]
The address should be at "りそーす"

P.S. Don't worry, I actually learn Japanese, and I understand the rest of written :fox_face:

**Comment by Wohlstand** [comment]
>  And, Do you know how to figure out the exact offset of OPL3 chip ?

Need to check out the specification on where the chip is located. If 0x380 offset won't work, then it should be another one (CMedia chips actually has it different)

**Comment by 110-kenichi** [comment]
Thanks! ありがとうございます！
I need to find out the I/O address range from [Resource]... Hmm...

**Comment by 110-kenichi** [comment]
I think that the FM address of my device is 388 or 398 or 3A0 or 3A8 .

![image](https://user-images.githubusercontent.com/40394569/152183908-94302990-b07f-43ab-bca8-35e885be7803.png)

So, I'd selected "Proxy to the real OPL3" for the chip type and set the hardware address value to both 388 & 398 & 3A0 & 3A8 and loaded sound samples.

However, I can't sound anything... Hmm... Any idea?

How to check inpoutx64.dll is working...

**Comment by 110-kenichi** [comment]
My sound card address is 0xf7500000 ?

![image](https://user-images.githubusercontent.com/40394569/152255680-eb4d5613-780c-4d09-a7eb-96152e56a872.png)

And also I used the setpci command to query some I/O addresses. 
The result is here. Hmm...

> .\setpci.exe -v -s 08:04.0 CB_LEGACY_MODE_BASE CB_IO_BASE_0 CB_IO_BASE_1 IO_BASE_UPPER16 IO_BASE
> 0000:08:04.0 @44 = 00041073
> 0000:08:04.0 @2c = 1073
> 0000:08:04.0 @34 = 0050
> 0000:08:04.0 @30 = 0000
> 0000:08:04.0 @1c = 00

**Comment by Wohlstand** [comment]
Looks like yes :thinking:

**Comment by 110-kenichi** [comment]
Sorry, where do I input the value 0xf7500000 ?

I can input 4 hex digits onlyt into dhis dialog box...
![image](https://user-images.githubusercontent.com/40394569/152275084-8494452b-88d2-499d-91a1-96b55f35deda.png)

**Comment by Wohlstand** [comment]
I could try to fix this, but, before, I want to ask some from @nukeykt what he knows about such things

**Comment by 110-kenichi** [comment]
Thanks @Wohlstand -san, @nukeykt -san !

NOTE:
I've checked the InpOut API. The port address type was ushort(16bit)...

> void _stdcall Out32(short PortAddress, short data)

Can we access a real OPL chip on x64/x86 windows ? I think the PCI BAR is 32bit.

**Comment by 110-kenichi** [comment]
Hmm. WinRing0 works on Win10(x64) to write/read data from IO ?

AutoHotKey uses WinRing0 to do that.
https://www.autohotkey.com/boards/viewtopic.php?f=6&t=9009&sid=d8bb6f2585cb75aafee9a6751212d3cd&start=20

**Comment by 110-kenichi** [comment]
I'll close it for now. ( I will investigation... )

**Comment by 110-kenichi** [comment]
Thanks all.

I could write a custom device driver for CMI8738(OPL3) for Windows11(x64) to sound OPL3.
If you would like to use my driver, please grab it here.
https://github.com/110-kenichi/mame/tree/master/src/CMI8738OPL3

And, I would like to support YMF724 card, too. But, it is so hard...
