### ISSUE TITLE
Piano wiev is broken on KDE theme

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#194]
So I now immediately noticed this:
![obraz](https://user-images.githubusercontent.com/32672779/210280330-862f08dc-a6eb-4cde-a81f-21709da61fab.png)

as you can see, the piano is completely white, save for a few pixels at the top of it. it is functional, but looks ugly.
KDE 5.26.4, Qt 5.15.7, X11

**Comment by Wohlstand** [comment]
Weirdo... try to run with the argument "-style fusion" to see what happen...

**Comment by freq-mod** [comment]
it works with fusion

**Comment by Wohlstand** [comment]
So, looks like a bug of the KDE's UI part, however, I should take a look is possible to work around that bug...

**Comment by Wohlstand** [comment]
Closing as abandoned. This needs to be debugged separately.

**Comment by Wohlstand** [comment]
Please re-open if problem is still actual.
