### ISSUE TITLE
Output VGM recording

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPL3BankEditor#198]
I hope to add the ability to record VGM, it will be useful.

**Comment by Wohlstand** [comment]
Do you want to record real-time play/steam? or convert a MIDI file?

For the second case, it's reasonable task for libADLMIDI, I need to resume some works that was started by @freq-mod (https://github.com/Wohlstand/libADLMIDI/pull/250). At the side of libOPNMIDI there is already VGM recorder was been made a while ago.

**Comment by denjhang** [comment]
I have been waiting for several years.

**Comment by Wohlstand** [comment]
Closing this as this task is more related to libADMIDI rather than to this bank editor.
