### ISSUE TITLE
Supports multi-chip emulation

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPL3BankEditor#199]
If it were possible to emulate more than 2 chips when experimenting with sound, many limitations would be lifted.

**Comment by Wohlstand** [comment]
The goal of bank editor's running chip is a preview of editing instrument, not using the bank editor as a real-time MIDI synthesizer. The [libADLMIDI](https://github.com/Wohlstand/libADLMIDI) works for such purposes. If you want to have a kind of combination of libADLMIDI and a simple bank editor, there is ADLPlug thing should help you: https://github.com/jpcima/adlplug)

**Comment by Wohlstand** [comment]
There will be possible to get multichip support once I decide to switch the whole playing backend into libADLMIDI itself rather than using a very simplified hand-made tester thing.

**Comment by Wohlstand** [comment]
As I replied at another issue, the bank editor's sound backend designed to be simple tester of currently-editing instruments, not as a full-featured MIDI synthesizer.
