### ISSUE TITLE
Sometimes refuses to save files

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#2]
When saving in DMX format, sometimes the file simply won't save. Even before saving, I click away from an instrument and back to the previous one and my changes are reverted.

I've saved 10+ times, and it still won't save after a while. Sometimes even instruments I didn't even touch change somehow (pair of 2op voices mode especially).

**Comment by Wohlstand** [comment]
Does that happens with latest version?

**Comment by sneakernets** [comment]
Nope, closing :)
