### ISSUE TITLE
Support midi multi-instrument

### ISSUE THREAD

**Issue by denjhang** [Wohlstand/OPL3BankEditor#200]
OPL3BankEditor currently seems to be able to test only one sound at the same time, I hope to support multi-instrument playback.

**Comment by Wohlstand** [comment]
For that it's reasonable to take the libADLMIDI as the backend. Current backend was been designed to be very simple to just test the currently editing instrument.

**Comment by Wohlstand** [comment]
Closing as abandoned. I would replace the internal core with the libADLMIDI that should allow such things. Again, current core of the OPL3 backend wasn't designed to be a full-featured MIDI synthesizer: only as a testing tool to verify sounding of currently-editing instrument.
