### ISSUE TITLE
Add support for MMDevice API or WASAPI instead of using ASIO.

### ISSUE THREAD

**Issue by gtr3qq** [Wohlstand/OPL3BankEditor#202]
ASIO is great! when just editing the banks.
But, I'd like to pair it with a tracker software to make some tunes.
This created a major inconvenience as all the other software is muted.

My system is a Win10 22H2 with Realtek onboard "sound card".
When OPL3BE is launched, well it takes over the whole sound card per ASIO standard.

I hope I didn't missed any docs about setting up drivers.
If so, pleas close this.
Thank you for your amazing software.

**Comment by Wohlstand** [comment]
Please try out the latest build of the OPL3BE, I already disabled the use of ASIO because of several reported problems including inability to launch the editor because of initialising failures,  etc.

**Comment by Wohlstand** [comment]
One of these issues is #188 and the confirmation that it got been fixed after ASIO support got been eliminaed: https://github.com/Wohlstand/OPL3BankEditor/issues/188#issuecomment-866641195

**Comment by Wohlstand** [comment]
Closing because everything had been solved:
- the WASAPI is being used by default on Vista+
- DirectSound or WinMM gets work as fallback on WinXP and older.
