### ISSUE TITLE
can't seem to merge drum and melody ibk files to a wopl.

### ISSUE THREAD

**Issue by zaphod77** [Wohlstand/OPL3BankEditor#210]
the two ibk files i'm working with are here.
http://annex.retroarchive.org/cdrom/nightowl-006/042A/MID2CMF.ZIP

i think the drum.ibk uses a lot f "default instruments" or something. these work fine with the included mid2cmf converter, but i can't get a peep out of them when i imort one intto the other and save a .wopl file.

So why isn't this working?

**Comment by Wohlstand** [comment]
Lemme take a look on this...

**Comment by Wohlstand** [comment]
Okay, now I am at my computer. So, that's because how IBK files are by theme selves: instruments do have the mark as "melodic" or "drum". And because of that, instruments marked as melodic fled into melodic set. Here is what you can do:
- Open the melodic bank as usually.
- Use the File / Import dialogue, then open the DRUMs bank into it (you can drag und drop it).
- Select these five drum instruments, and import them into the Drums slot

These instruments, seems, needs a manual adjustment, because they are clucky at the source (they are same when you open this drum bank via sbtimbre, I checked that), you need to manually tweak them manually: set them a rhythm mode drums, and set the note, and also, seems, adjust some other properties to make them valid :thinking:

**Comment by zaphod77** [comment]
then why do they WORK with mid2cmf?

i want to play back this midi file and have it sound like this

https://www.vgmpf.com/Wiki/index.php?title=Ballad_2

if i load melody.ibk (or the alternate mt32.ibk with sbtimbre) then i can play ballad2.mid is dosmidi with 

dosmid /opl /sbnk:melody.ibk ballad2.mid

but if i leave off the drum one, the drums play back differently.

if i use drum.sbk from sbbtimbre, that doesnt' help any.

**Comment by Wohlstand** [comment]
> then why do they WORK with mid2cmf?

Because there are hardcoded conditions that use these instruments differently than they are in the bank file.

**Comment by zaphod77** [comment]
anyway turns out the midi file is an actual mt-32 arrangement, and windows itself was getting the percussion wrong anyway, but i still need a mt32 percussion fm .ibk to go with melody.ibk, as drum.ibk from sbtimbre isn't that.

i tested this by sending it out to MUNT, and the percussion is better there, and seems to have more different instruments.  seems it's going to take much reverse engineering to fix this.

**Comment by Wohlstand** [comment]
Anyway, the tool doesn't remaps instruments, and here is a result thing I did with my custom GM melodic set, but kept drums as original:
[MID2CMF-xiang.zip](https://github.com/user-attachments/files/16419393/MID2CMF-xiang.zip)
To make drums work, the channel 10 should set patch `126`.

**Comment by zaphod77** [comment]
here's my other reference that the file is supposed ot be for mt-32

https://www.vgmpf.com/Wiki/images/d/d3/Voyetra_-_Sequencer_Plus_and_MusiClips.pdf

last page says so.

**Comment by zaphod77** [comment]
finally reaad the manual.  mt-32 drum map is not exactly a subset of gm drum map. it's similar, but not identical.

specifically, the bass drum and tom sounds are not the same.  everything else pretty much matches.

**Comment by zaphod77** [comment]
okay, merged in fat_drums.sb (the fat man's 2 op drum patchset) to the mt32.ibk, and this actually sound decent.  it's not the same as the actual windows recording, but turns out windows 3.1 was wrong anyway.

**Comment by Wohlstand** [comment]
Speaking about Windows 3.1, if you are interested, I have the "MS Adlib" bank extracted from the source code of the AdLib and SoundBlaster 1.x drivers for Windows 3.1 (they shared the same MIDI driver code, and the same bank) and I turned it into WOPL.
[msadlib.wopl.zip](https://github.com/user-attachments/files/16420331/msadlib.wopl.zip)

**Comment by zaphod77** [comment]
nope, that's the new one that is gm.

the driver i'm talking about has an mt-32 melodic bank.

it came on the sb 2.0 driver disks. any ones that HAVE those four midi files (ballad2, jazz3, minuet1, and reggae2) on it has the correct driver.  and it don't have source.

**Comment by zaphod77** [comment]
https://archive.org/download/creativelabssoundblaster2.0/Creative%20Labs%20Sound%20Blaster%202.0.zip the driver is here.

**Comment by zaphod77** [comment]
anyway i manage dot geg win e3.11 working in dosbox, used the setup with that driver to install the driver, and jukebox.exe does play the midis. the bank is either in sndblast.drv, or in jukebox.exe itself. hopefully you can figure out how the heck to get it out.

and yes, whe ni do that, ballad2.mid sounds just liek it did on that website. EXACTLY. playcmf isn't quite the same.
