### ISSUE TITLE
No sound output on my "2- High Definition Audio Device" on Windows 10

### ISSUE THREAD

**Issue by Kitsune64** [Wohlstand/OPL3BankEditor#216]
Hi,

I can't have output sound on "2- High Definition Audio Device" on Windows 10 with OPL3BankEditor.

I have tried differents chips simulator for OPL3, but I don't have any sound.

Also I have attempt to run it in a virtual Machine through Qemu with Windows 98 guest and it work (with AC97 emulation) so wath can I do for make it work in navite Windows 10?

Thanks.

**Comment by Wohlstand** [comment]
Hello! This looks weird, on my end it works on a wide variety of operating systems, and on Windows it should work on Windows 10 as well as on XP (The Win98 version is very special, and it should not used on Win10 as it uses legacy APIs, and there are chances that its support was broken for your audio drivers :thinking:).

**Comment by Kitsune64** [comment]
I have find where come from the issue.
It was ReaRoute ASIO Drivers that may conflict with my sound card in BankEditorOPL3.
ReaRoute ASIO Driver can be installed with the Reaper (mixing, sequencer) audio software, I think is for low latency work on audio mixing. Apparently this driver can make mess on other softwares.

I have uninstalled Reaper...Now I can see the name of my conventional audio device in your software, I select it and the sound work now.
