### ISSUE TITLE
Window layout does not work well

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#26]
It's not a big deal and doesn't really hurt the functionality of the program.
But there is a lot of strange spacing everywhere, widget heights that don't fit, truncated texts, etc..
An irritating point is not being able to resize the window to give it more space to arrange its stuff.

It must depend on the theme and user's font how well these things must be laid out on screen.

There is screen shot to illustrate a number of badly displayed elements.

![obe](https://user-images.githubusercontent.com/17614485/38656169-12d7bda8-3e19-11e8-9ce3-1fb1242b1241.png)

**Comment by Wohlstand** [comment]
Or that means I need to take some font into resources and use it. Anyway, the development of layouts for different platform is hacky, and on macOS is similar issue as your.
