### ISSUE TITLE
Sound can distort/garble

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#3]
Rarely sound distorts heavily after saving files and playing notes for a period of time. Shaking the window seems to help (??) but after a few minutes, acts up again. I have to restart the program, and even then sometimes it starts up garbled.

**Comment by Wohlstand** [comment]
Which operating system you are using where you have this trouble? On Linux and on Windows XP / 7 I  have no problems with sound (I guess, you have Windows 10 because of your false positive report). I have to uploaded fresh update for Windows, please try out it

**Comment by sneakernets** [comment]
Alright, thanks, I will check that out.

**Comment by sneakernets** [comment]
Not happenening anymore, gonna say it's been fixed.
