### ISSUE TITLE
Importing single instruments can overwrite the wrong instrument

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#4]
Rarely, importing an instrument overwrites an instrument that wasn't selected, but was edited during that session.

**Comment by Wohlstand** [comment]
Does that happens after file open or toggling melodic and percussion?

**Comment by sneakernets** [comment]
Toggling., sometimes toggles from other imports are still there. I caught it in time, as I almost overwrote an instrument I just edited.

**Comment by Wohlstand** [comment]
I think I have been fixed that (there was another bug when you have just imported, edited, but in fact, you have edited the import cache and selecting another instrument with selecting just-imported instrument back, you can see TRUE instrument data). Try out the latest build and tell me, are you still have that?

**Comment by sneakernets** [comment]
I'll check that now. I appreciate all this, by the way. This is *the* best editor for OPL I've ever used.

**Comment by sneakernets** [comment]
This has been fixed.  boom. thanks.
