### ISSUE TITLE
Instrument names have bad characters

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#43]
The instruments "Lead 3 (Calliope)" and "Lead 4 (Chiff)" have a non-ASCII 'C'-like character.
Is this a cyrillic C letter? I have noticed that when I used your instrument name list and it printed funny characters in the terminal.

I don't know if other instruments have this in their names.

I don't know what's wrong with Github right now I can't push. Posting this as issue.

**Comment by Wohlstand** [comment]
I think, yes, there are Cyrillic and it's possibly made by mistake... Cyrillic has many letters are equal Latins partially or 1:1.


Отправлено с Samsung Mobile

-------- Исходное сообщение --------
От: JP Cimalando <notifications@github.com> 
Дата:11.05.2018  21:01  (GMT+03:00) 
Кому: Wohlstand/OPL3BankEditor <OPL3BankEditor@noreply.github.com> 
Копия: Subscribed <subscribed@noreply.github.com> 
Тема: [Wohlstand/OPL3BankEditor] Instrument names have bad characters (#43) 

The instruments "Lead 3 (Calliope)" and "Lead 4 (Chiff)" have a non-ASCII 'C'-like character.
Is this a cyrillic C letter? I have noticed that when I used your instrument name list and it printed funny characters in the terminal.

I don't know if other instruments have this in their names.

I don't know what's wrong with Github right now I can't push. Posting this as issue.

**Comment by jpcima** [comment]
I am familiar with the cyrillic alphabet and I know how to read most of it.
But to make the visual distinction between latin C and cyrillic C.... this has been a head scratching moment. :smile:
Github is still not wanting to let me push..
