### ISSUE TITLE
Playing keyboard without instrument loaded may crash

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#46]
Just load the software with no instrument and press a piano key. (either keyboard or midi)
Invalid access found by the address sanitizer.

In NoteManager it has out-of-bounds on first access of the channel array, because size is 0. 
`if(channels[chan].note == -1)`

**Comment by Wohlstand** [comment]
Damn! it's a mistake, gotta to fix...
Same crap is possibly on OPN2 Bank Editor too...

**Comment by Wohlstand** [comment]
For now I gonna to rework Generator to move real chip communication into separate place and allow switching between of real chip and the emulator, but seems some other projects I doing now and I partially busy now...

**Comment by Wohlstand** [comment]
About of the bug: when no instrument loaded, I must to reject ANY coming note events until I'll load the instrument

**Comment by jpcima** [comment]
No matter if you're busy I can surely fix this.
I implemented my key filter and thought my code was doing wrong!
Thanks god for adress sanitizer software, guys who invented this deserve a medal for this stuff.
