### ISSUE TITLE
Latest beta release seen as trojan under Windows 10

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#5]
If I try to download the release, windows defender deletes them because it says that they contain "win32/spursint.a".  [Yet analysis says it's not infected](https://www.virustotal.com/en/file/3da836888078da00f79e5f9a851ffab59cccd021447b73bce98f53af2475c8ca/analysis/).

**Comment by Wohlstand** [comment]
I thin, it's time to rebuild the assembly, because it is outdated and I have many things updated since latest release, wait a sec, I'll add AppVeyor support

**Comment by Wohlstand** [comment]
Try out this build for all issues you had opened: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/opl3-bank-editor/opl3-bank-editor-dev-win32.zip

**Comment by sneakernets** [comment]
This works! thanks!

**Comment by Wohlstand** [comment]
So, I'll close this
