### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#59]
I have started a translation of OPL3BankEditor, because there are a french community who have an interest in integrating the OPL3 stuff in the Linux distribution [LibraZik](http://librazik.tuxfamily.org/).
There isn't an established system for translating so I have also worked on adding this too.
I have a branch `traduction` which is about half way done, except installing everything properly. For windows, we should arrange releases to include the translations in their package, and to search for them in installation folders.

OPN2BankEditor should not take as much effort to repeat this work, because the programs share a lot of their text in common.

:fr: :wine_glass: :rooster: :frog: 

- [X] translating the messages
- [X] creating an installation process (only CMake)
- [X] adding a dynamic language choice in menus
~~arranging the layout of the import dialog~~

**Comment by Wohlstand** [comment]
Nice! Once I need to put the translation loader thing from my PGE Editor's code... I'll also give Russian translation from me

**Comment by Wohlstand** [comment]
I mean, the dynamical re-translation thing with ability to switch language on a fly

**Comment by jpcima** [comment]
Then I'm going to look at this program as example. For testing I just stored the translation data in qrc.
It's not necessary to have a language switch though, because Qt can do a selection based on locale.

**Comment by Wohlstand** [comment]
That yeah, but the case when you want to switch another language - usually for a test or for screenshots

**Comment by jpcima** [comment]
A thing I almost forgot about: the importer dialog needs the layout redone as well, it has text overflows on my screen, and it gets worse on french text which is longer.

**Comment by Wohlstand** [comment]
You would to create a separate module or file where you will store the translation related code. In the menu, create the Help->language menu which will be empty. Then, fill the menu dynamically with existing language files. Myself I also using flags in PGE Editor.

**Comment by Wohlstand** [comment]
For the QMake stuff it's the "Installs" thing:
http://doc.qt.io/qt-5/qmake-advanced-usage.html

You may need to allow passing variables from the command line:
https://stackoverflow.com/questions/45884125/how-to-pass-a-qmake-variable-from-the-command-line
And when is nothing defined, just pass the default value, I.e. most common "/usr/local/" thing... :wink:

**Comment by jpcima** [comment]
I have not added install rules in qmake, there weren't any in the first place apparently.
But in definitive as a solution I have just found this.

`    QString appTranslationDir =
        QCoreApplication::applicationDirPath() + "/../share/opl3_bank_editor/translations";`

**Comment by Wohlstand** [comment]
One thing it is not so good for macOS case. Instead, you will need to use in-bundle resources where translation files will be packed. So, you may have the list of paths and look up it entirely:
```
./translations
../share/opl3_bank_editor/translations
macosResources() "/translations" /*Use right function that returns path to in-bundle resources*/
```

**Comment by jpcima** [comment]
Where is the translations directory related to the executable in the Mac bundle structure.
Can I deduce it relative to `QCoreApplication::applicationDirPath()` ?

**Comment by jpcima** [comment]
I looked at a MacOS bundle made with Qt `krita.app`.
There is `Contents/MacOS/krita` (binary) and `Contents/Resources/translations`.
So I assume code below is correct.

```
#if defined(Q_OS_WIN)
    QString qtTranslationDir = QCoreApplication::applicationDirPath() + "/translations";
    const QString &appTranslationDir = qtTranslationDir;
#elif defined(Q_OS_DARWIN)
    QString qtTranslationDir = QCoreApplication::applicationDirPath() + "/../Resources/translations";
    const QString &appTranslationDir = qtTranslationDir;
#else
    QString qtTranslationDir = QLibraryInfo::location(QLibraryInfo::TranslationsPath);
    QString appTranslationDir =
        QCoreApplication::applicationDirPath() + "/../share/opl3_bank_editor/translations";
#endif
```

**Comment by jpcima** [comment]
To make Linguist translations available outside of the Qt world is definitely interesting.
It needs the cmake macros to go with it and it's perfect. (and need to build mingw gettext, link in mingw libintl is finished)

**Comment by jpcima** [comment]
Do you expect of me to add more things? I don't know if you wait for something of me. You have mentioned a thing about completing some work, which I have not understood.

You have pushed in the branch too some incomplete things which I don't understand either.
Qmake has some mention of a russian translation but there is no relevant translation file that I see in this commit.

**Comment by Wohlstand** [comment]
I'll continue my things later, so, take the stuff and I'll wait for you, then I'll test the stuff. For now I have some work on PGE Editor where I must to fix one weird crashing...

**Comment by jpcima** [comment]
I have merged your branch, added russian to cmake, and the untranslated ts file.

**Comment by Wohlstand** [comment]
My Russian translation is almost-completed as some strings I wasn't finished yet, but I'll finish them tomorrow, for now I'm a bit tired and gonna sleep

**Comment by Wohlstand** [comment]
Damn, I have found I have made some typos in my translation :yum:
Need to fix that...

**Comment by Wohlstand** [comment]
Okay, just now I have completed my Russian translation, everything is now completed!
If anyone wants to add one another language support, that will be a separated issue.

**Comment by trebmuh** [comment]
:+1:
