### ISSUE TITLE
DMX: Percussion corrupts when saved

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#6]
On the new beta I downloaded this week, percussion is pretty much destroyed when I saved. I lost all my drums. :\

file here: https://github.com/sneakernets/DMXOPL/blob/master/GENMIDI.op2

older file with drums: https://github.com/sneakernets/DMXOPL/blob/09fd1ce689910e9df08d0fd0c7f27064df1d8180/GENMIDI.op2

**Comment by Wohlstand** [comment]
That strong... wait a sec....

**Comment by Wohlstand** [comment]
That weird, I had to open source bank, then I had to save it back, and then reopened editor and got drums fine. Very weird... 🤔 
What did you do after opening the file, and before you saved file? Maybe the associative import is glitchy (there are two options for import: associative to replace instruments by similar ID in same bank, and replacing one selected instrument)

**Comment by Wohlstand** [comment]
Okay, I think, I can understand why drums are broken: possibly TmpBank class did the damage.
Oh, yeah, 🤦‍ I know what happen: I accidentally used the uninitialized array as source while saved bank, will fix that

**Comment by Wohlstand** [comment]
Fixed, try out the fix! 😉

**Comment by sneakernets** [comment]
thanks, will do! You'll be credited in my DMX bank release. Hopefully it can be included in ADLMidi in the future...

**Comment by Wohlstand** [comment]
> thanks, will do! You'll be credited in my DMX bank release. Hopefully it can be included in ADLMidi in the future...
Yeah, I'll include that, and also I going to rework it with making it be real time MIDI playing library and make MIDI player be a separated library/application that uses ADLMIDI core and keeps the set of banks

**Comment by Wohlstand** [comment]
P.S. Use the same link to download fresh version, because Appveyor uploads that automatically, and I'll add that link into readme

**Comment by sneakernets** [comment]
thanks :D

**Comment by Wohlstand** [comment]
Please confirm that bug is gone on your side, and I'll close this

**Comment by sneakernets** [comment]
I'll check ASAP, I'll likely be able to check in the morning. My main computer is only accessible in the daylight hours.

**Comment by sneakernets** [comment]
FIXED.

**Comment by sneakernets** [comment]
I think I've run into YET ANOTHER PROBLEM with this. Check this out. First playthrough is with ADLMidi, the 2nd is with Doom.exe. What the heck? My hats aren't doing right at all 😢  

https://vocaroo.com/i/s1dOHs21EQ9J

**Comment by Wohlstand** [comment]
Does OPL3 wave forms are working with vanilla Doom? I bet, if it tries to set OPL2 mode, those voices would be turned off. Doom usually turns OPL2 mode with 9-voices mono mode

**Comment by sneakernets** [comment]
Yes, OPL3 waveforms work with vanilla Doom, but these hats aren't using OPL3 waveforms, so that can't be it. :\

**Comment by sneakernets** [comment]
Here's the file that was used: 
[GENMIDI.zip](https://github.com/Wohlstand/OPL3BankEditor/files/1277983/GENMIDI.zip)

**Comment by sneakernets** [comment]
The ones in question are Closed High-Hat, Pedal High-Hat, and Open High-Hat

**Comment by Wohlstand** [comment]
Did you tested Doom on real hardware or on emulator?

**Comment by Wohlstand** [comment]
Nuked OPL3 even is very accurate, DosBox's emulator is not, therefore needs a different pitch to have right sounding, hihats are very sensitive

**Comment by sneakernets** [comment]
I've used real hardware to test it (my Toshiba laptop), nuked's OPL3 core as well.

**Comment by Wohlstand** [comment]
Just for a test, try to use Windows 98 version of my bank editor, it uses OPL3 chip directly

**Comment by sneakernets** [comment]
Yeah it's fine! I used SLADE to look at the GENMIDI and on my closed hi-hat, it claims note offset is -7 instead of 5 on the second voice, and -12 on the first voice (instead of 0). I could be reading this wrong, but I'm going to modify it manually with slade and see if I can "fix" it.

**Comment by sneakernets** [comment]
One quick question, can I save my `op2` as another format and then convert that back when/if there is a fix for this? I don't wanna lose the `GENMIDI` I've made so far. 😥

**Comment by Wohlstand** [comment]
You can use my WOPL format which I created to support everything supported by editor.

**Comment by sneakernets** [comment]
awesome.
