### ISSUE TITLE
Extend the MIDI support

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#69]
To follow up on support of MIDI input #19 

I have created a public document to keep track of MIDI support, and the future things to consider for addition. On page 1 there are general items, and page 2-3 the controller support.

[MIDI Implementation Chart](https://docs.google.com/spreadsheets/d/1-HN3P6wX0GzThnP2d5CrD_Y7sh_X33ZpNaXcIm0h0Og/edit?usp=sharing)

I have currently one item in the state "Requested" (CC74 brightness).
Discuss other items there is interest in having added.

**Comment by jpcima** [comment]
> I would also write some notes into this document too ;3

@Wohlstand Let's do this in reverse if you don't mind. Take a copy of the document on your account, and add me to it. You have my mail on my profile webpage.

**Comment by Wohlstand** [comment]
I think, I'll even make the milestone for this

**Comment by Wohlstand** [comment]
And, I think, I'll join you access to this repo to let you manage labels, create branches, etc. However, for safety, let's use pull-requests as review system. I.e. many any experimental thing and then push it to master through pull request inside of the same repo. Or, for convenience, you can still use own forked repo for everything.

**Comment by jpcima** [comment]
Controllers I have added:

- [X] CC#7 channel volume
- [X] CC#11 expression MSB

> What is the sense of velocity on note offs?

It's explained in MIDI spec as "Release velocity". It acts like a modifier of the release time of the envelope.

**Comment by Wohlstand** [comment]
Closing as abandoned. If something needed, please re-open.
