### ISSUE TITLE
First try building OPL3BE - jackd (and pulse) question

### ISSUE THREAD

**Issue by trebmuh** [Wohlstand/OPL3BankEditor#73]
_Build from today's https://github.com/Wohlstand/OPL3BankEditor/commit/440bd3bf87340b497ea0eb3d5a88d30ebcec40c8_

Hi,
I had a try this afternoon at building a .deb package for OPL3BE. I've got the GUI launching and the translation working. Good job at getting the translation system working, and specially for the user to be able to switch the GUI translation without having to restart the software!

I've got little-to-no knowledge about OPL stuff and I'm trying here to have a great package for my users who are working with that (I'm the LibraZiK dev) since I recently added ADLjack from @jpcima . Now, I'm trying to understand how this soft is supposed to work.

First, when I'm launching it from the command line, I've got this:
```
Init audioOut...
Using RtAudio API 1
Desired latency 0.02
Buffer size 960

RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.


RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.

Init Generator...
Init Rt-Generator...
Seting pointer of RT Generator...
Init signals and slots of keys...
Trying to start audio... (with dereferencing of RtGenerator!)
Trying to start stream...
Stream started!
Trying to init MIDI-IN...
```

The `Device or resource busy` looks to indicate that OPL3BE is trying to start with ALSA, but on my (audio-tuned) system, jackd is already launched.

Note that if I'm closing jackd, I've got this:
```
$ opl3_bank_editor 
Init audioOut...
Using RtAudio API 1
Desired latency 0.02
Buffer size 960
Init Generator...
Init Rt-Generator...
Seting pointer of RT Generator...
Init signals and slots of keys...
Trying to start audio... (with dereferencing of RtGenerator!)
Trying to start stream...
Stream started!
Trying to init MIDI-IN...
```
which sounds to be fine.

I saw in the [makefile](https://github.com/Wohlstand/OPL3BankEditor/blob/master/CMakeLists.txt#L31) that there seems to have the possibility for OPL3BE to work with jackd or pulse. I didn't find any confirmation of that in the [wiki](https://github.com/Wohlstand/OPL3BankEditor/wiki), and there is no manpage if I'm correct.

To give it a try, I've added the -dev packages as build-dependencies on my package with my finger crossed that the jackd and pulse build supports would then be automatically handled if the dev package are found during the build. Unfortunately, it doesn't seem to be the case.

Does this need me to add a configure option (or something similar) for the support to be added?

**Comment by jpcima** [comment]
Let me try to explain this shortly: the audio support is built on RtAudio libraries, which supports not only Jack but also the other audio interfaces of Linux (pulse, ALSA).
In a single program, it builds all these interfaces at once, and when run it will pick the one which matches the system best, in your case Jack.

But as your console shows, you're not getting Jack. There is a reason to that: you are likely using the QMake build, in which the detection of Jack libraries is not supported, so you are left with ALSA only.

It's a simple fix: build the program with CMake. If Jack is found the feature summary is going to show you this:
```
!!   -- Jack driver: 1
```

**Comment by trebmuh** [comment]
Thanks @jpcima 
I've been building it with 
```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
make
```
as you suggested, and everything goes well now.
Closing here.

@Wohlstand : it could/should be put in the README or in the wiki. Let me know the best place from your POV and I'll put it there for other people.

**Comment by jpcima** [comment]
@trebmuh I never even knew we have a wiki, but apparently we do. :grin: 
Since there exists a link to a page named "Building from sources", I guess it would be an appropriate place to keep this information.

**Comment by trebmuh** [comment]
@Wohlstand @jpcima : mmm, unfortunately github tells me that `You do not have permission to update this wiki. ` when trying to create/edit the "Building from sources" page. So I'm stuck here.

**Comment by Wohlstand** [comment]
@trebmuh, then it's I need to give you an access

**Comment by Wohlstand** [comment]
But okay, just now I have allowed everyone edit them.

**Comment by jpcima** [comment]
I created this info page just now. @Wohlstand  It can be nice to edit README on the front page to link this or somewhat reflect the new build steps with CMake.

https://github.com/Wohlstand/OPL3BankEditor/wiki/Building-from-sources

**Comment by trebmuh** [comment]
:+1:
