### ISSUE TITLE
 First try building OPL3BE - first try using the soft

### ISSUE THREAD

**Issue by trebmuh** [Wohlstand/OPL3BankEditor#74]
_Build from today's https://github.com/Wohlstand/OPL3BankEditor/commit/440bd3bf87340b497ea0eb3d5a88d30ebcec40c8_

My first try using this software.
_I don't really know how it is supposed to work, excuse the probable newbie question here._

1) I'm launching the software from the command line (Debian Stretch)
2) the GUI appears (and in French, thanks for that guys!)
3) I'm loading a random bank (the _warcraft_ one from the Bank_Examples/ folder)
4) I'm clicking on the GUI's virtual keyboard
...no sound out.

What should I do?

@jpcima : you're welcome to answer me in French here, or to talk with me on IRC (#librazik or #linuxmao on freenode - my nicks there are trebmuh and olinuxx)

**Comment by jpcima** [comment]
See #73 for the answer on building RtAudio with Jack.
The audio output will then work in Jack, and you will have to select a port in the top right corner of the window to make it appear in ALSA MIDI.

**Comment by trebmuh** [comment]
Thanks for the help @jpcima 
It does work as expected and is producing sound now.
Closing then.
