### ISSUE TITLE
Bank Dropdown is hard to read

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/OPL3BankEditor#88]
Hi,

A change a while back has made the bank select dropdown harder to read.
![dropdownmenu](https://user-images.githubusercontent.com/5595293/42329034-707d1148-8035-11e8-9216-5bafcd239b0a.png)

I'm using the latest build as of 5 July.

**Comment by Wohlstand** [comment]
This is very common crap with ComboBox in Qt, and it's the workaround to show full labels, I applied it to PGE Editor here: https://github.com/WohlSoft/PGE-Project/blob/master/Editor/common_features/proxystyle.cpp

**Comment by jpcima** [comment]
Reporting success with virtualized Windows 7.

![test](https://user-images.githubusercontent.com/17614485/42332943-a848d596-8079-11e8-92e3-faf2fad0dfc8.png)

**Comment by Wohlstand** [comment]
So, it's only needed a confirmation from @sneakernets as he is know about of this fix :wink:

**Comment by sneakernets** [comment]
That did it! thanks!
