### ISSUE TITLE
Can't load HMI bank d2melo.bnk

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#92]
It's impossible to load either of banks `d2melo.bnk` or `d2drum.bnk`.
It says unsupported file format. Other HMI files work.

**Comment by Wohlstand** [comment]
Can you attach those files to analyze?

**Comment by jpcima** [comment]
Genadldata converts these files.
It's out of the libADLMIDI directory: fm_banks/bnk_files/

**Comment by Wohlstand** [comment]
Oh, there... But wait... Are there AdLib Gold formats?

**Comment by Wohlstand** [comment]
It's not yet AdLib GOLD banks support yet, and there are different format

**Comment by jpcima** [comment]
In the `banks.ini`, I see the files indicated as HMI format, not AdLibGold
```
[bank-6]
name     = "HMI (Descent 2)"
format   = HMI
file     = "fm_banks/bnk_files/d2melo.bnk"
file-p   = "fm_banks/bnk_files/d2drum.bnk"
prefix   = "b6M"
prefix-p = "b6P"
```

**Comment by Wohlstand** [comment]
Gotta to check...

**Comment by Wohlstand** [comment]
Ha-ha! I know why!
Look:
![default](https://user-images.githubusercontent.com/6751442/44882371-aad8d900-acbb-11e8-9610-214f575aeeff.png)

Because of this, the detector fails to identify this file as AdLib BNK/HMI

**Comment by Wohlstand** [comment]
Fixed!

**Comment by jpcima** [comment]
I took your code for my genwopl in the works, and it has now loaded the d2 banks.
Thanks :smiley:

**Comment by Wohlstand** [comment]
Closed as it's tested and fixed!
