### ISSUE TITLE
Can't load AIL bank fm_banks/opl_files/sample.opl

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/OPL3BankEditor#93]
It's failing at this point with a size check, with `insLen` of value 226.

https://github.com/Wohlstand/OPL3BankEditor/blob/6c0d2404844e4127717b4108dcdeced489cc3df4/src/FileFormats/format_ail2_gtl.cpp#L173-L177

**Comment by jpcima** [comment]
Disregard my old comment about a too small buffer, as I missed a line of code `insLen -= 2`.
I can make the reading pass by taking the 24 head bytes and skipping the rest; however it's to check if the result are going to be valid instruments.

**Comment by Wohlstand** [comment]
Let's check how XPlay (XMIDI player from AIL2 set) deals with it:

[xplay-src.zip](https://github.com/Wohlstand/OPL3BankEditor/files/2338405/xplay-src.zip)

**Comment by Wohlstand** [comment]
I have made the quick experiment, and it have opened the bank, but, the junk crap have appeared in "Bank 1"

**Comment by Wohlstand** [comment]
Still need to analyze the thing...

**Comment by Wohlstand** [comment]
Closing as abandoned. If something needed, pleas re-open.
