### ISSUE TITLE
Some instruments sound incorrectly after loading DMXOPL bank

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/OPL3BankEditor#94]
Steps to replicate:
- take @sneakernets' GENMIDI (GS).wopl bank file
- select "Electric Piano (DX-7)" instrument 
- it won't sound correctly. Muting operators 1 and 2 reveals that operators 3 & 4 seem to be interpreted incorrectly (?), almost like operator 3 had frequency mult. value of 6 while it has 1
- oh wait. Muting all operators should result in silence? Not the case. You can still hear a faint sound.

Took the newest bank editor from the repo. Issue present using both Nuked and Dosbox emul cores.

**Comment by Wohlstand** [comment]
In the `NoteOn` in `src/opl/generator.cpp` seems a bug... Damn! Pseudo-4op instruments will use fmult from first voice!
I'll check out stuff at evening...
The same bug is 1:1 got libADLMIDI!

**Comment by jpcima** [comment]
I believe the patch above to be working. It's to check
I don't think libADLMIDI is hit by such a bug. It's picking the patch in a sort of cache which is mapped by the chip channels.

```
    const adldata &patch1 = m_insCache[c1];
    const adldata &patch2 = m_insCache[c2 < m_insCache.size() ? c2 : 0];
```

**Comment by papiezak** [comment]
About FMULTs - yes, thanks for the fix @jpcima!

However there is another weird crap that I mentioned in issue post - setting levels of all operators to 0 should effectively make instrument mute? Because I can still hear notes, they're very quiet, though.

**Comment by jpcima** [comment]
@papiezak From datasheet, a maximum TL would represent -47.25 dB attenuation.
I think OPL3-BE shows TL as inverted control, like a volume.
So it's possible for signal not to be entirely silent, I guess.

**Comment by papiezak** [comment]
Then I guess it's safe to assume everything's fine then
